
STRINGS = GLOBAL.STRINGS
STRINGS.NAMES.MUSHA = "Musha"
STRINGS.CHARACTER_TITLES.musha = "The Puppy Princess, Musha"
STRINGS.CHARACTER_NAMES.musha = "Musha"
STRINGS.CHARACTER_DESCRIPTIONS.musha = "Level(L) Skill(K) Visual(P) Sleep(T) Shield(C) Valkyrie(V) Strike(R) Music(U) Shadow(G) Yamche(X) Battle(Z) Gather(B) Dall(N) Arong(Y)"
STRINGS.CHARACTER_QUOTES.musha = " I am a true Princess! "

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSHA = ("Maybe, she can join my books club.")
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MUSHA = ("Royal blood? Hmm...")
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MUSHA = ("She can transform?... No, maybe not.")
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MUSHA = ("She is weak force... but, seems like she can help us.")
STRINGS.CHARACTERS.WENDY.DESCRIBE.MUSHA = ("I feel a strong spirit within her...")
STRINGS.CHARACTERS.WX78.DESCRIBE.MUSHA = ("I feel my heart.")
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA = 
{
GENERIC = "Feels good!",
ATTACKER = "Fight fight fight",
MURDERER = "Assassin!",
REVIVER = "Return...",
GHOST = "Go away!",
}

--status
STRINGS.MUSHA_LEVEL_NEXT_LEVEL_UP = "Next Level Up"
STRINGS.MUSHA_LEVEL_LEVEL = "Level "
STRINGS.MUSHA_LEVEL_EXP = "[EXP]"
STRINGS.MUSHA_LEVEL_SLEEP = "Sleep"
STRINGS.MUSHA_LEVEL_TIRED = "Tired"
STRINGS.MUSHA_LEVEL_MUSIC = "Music"
STRINGS.MUSHA_LEVEL_SNIFF = "Sniff"
STRINGS.MUSHA_SLEEP_TIRED = "[Sleep ◑ Tired]"
STRINGS.MUSHA_VISUAL_BASE = "[Base Visual]"
STRINGS.MUSHA_BADGE_SLEEP = "[Sleep     badge]"
STRINGS.MUSHA_YAMCHE_DEBUG = "[Debug]\nDrop Everything"
STRINGS.MUSHA_MUSIC_DYNAMIC = "[Dynamic Music]♪\n:Random"
STRINGS.MUSHA_MUSIC_DYNAMIC_OFF = "[Dynamic Music]♪\n:OFF"
STRINGS.MUSHA_DEATH_PENALTY = "[Death]\n[EXP]"

STRINGS.MUSHA_SKILL_ACTIVE  = "[------Active Skill------]"
STRINGS.MUSHA_SKILL_SLEEP   = "Sleep◑Wake up"
STRINGS.MUSHA_SKILL_POWER   = "Power Lightning"
STRINGS.MUSHA_SKILL_SHIELD  = "Spark Shield"
STRINGS.MUSHA_SKILL_MUSIC   = "Music♪"
STRINGS.MUSHA_SKILL_SHADOW  = "Hide in the Shadows"
STRINGS.MUSHA_SKILL_PASSIVE = "[------Passive Skill------] "
STRINGS.MUSHA_SKILL_VALKYR  = "Valkyrie"
STRINGS.MUSHA_SKILL_BERSERK = "Berserk"
STRINGS.MUSHA_SKILL_ELECTRA = "Electric Shield"
STRINGS.MUSHA_SKILL_CRITIC  = "Critical Hit"
STRINGS.MUSHA_SKILL_DOUBLE  = "Double Damage"
STRINGS.MUSHA_T_SKILL_UNLOCK = "Unlock:"
STRINGS.MUSHA_T_SKILL_VALKYRIE = "Valkyrie"
STRINGS.MUSHA_T_SKILL_V_LIGHTNING = "Auto Lightning"
STRINGS.MUSHA_T_SKILL_V_POWER = "Power Lightning"
STRINGS.MUSHA_T_SKILL_V_ARMOR = "Valkyrie Armor"
STRINGS.MUSHA_T_SKILL_V_LIGHTNING = "Valkyrie Lightning"
STRINGS.MUSHA_T_SKILL_UP_ACTIVE = "Upgrade [Active Skills]"
STRINGS.MUSHA_T_SKILL_CRITICAL = "Critical Hit"
STRINGS.MUSHA_T_SKILL_E_SHIELD = "Electric Shield"
STRINGS.MUSHA_T_SKILL_BERSERK = "Berserk"
STRINGS.MUSHA_T_SKILL_B_ARMOR = "Berserk Armor"
STRINGS.MUSHA_T_SKILL_DOUBLE = "Double Damage"

--TALK
STRINGS.MUSHA_TALK_READY_POISON = "Poison Attack Is Ready!"
STRINGS.MUSHA_TALK_CANCEL_POISON = "Musha changed her mind..."
STRINGS.MUSHA_TALK_NEED_SANITY = "Musha needs more: [Sanity]"
STRINGS.MUSHA_TALK_NEED_SLEEPY = "Musha can't concentrate... Musha is too tired..."
STRINGS.MUSHA_TALK_NEED_SLEEP = "Musha needs to sleep more!"
STRINGS.MUSHA_TALK_NEED_EXP = "Musha needs more EXP!"

STRINGS.MUSHA_TALK_GRRR = "Grrr...!"
STRINGS.MUSHA_TALK_GHOST_REVENGE = "Ooooh ! Reeeeveeengeeee !!"
STRINGS.MUSHA_TALK_GHOST_OOOOHHHH = "Oooohhhhh.!!"
STRINGS.MUSHA_TALK_GHOST_OOOOH = "Ooooh...."
STRINGS.MUSHA_TALK_GHOST_MUSIC = "Oooh~♪ Ohoooh~♪"
STRINGS.MUSHA_TALK_GHOST_SLEEP = " .. Sleeeeepyeeee .. "
STRINGS.MUSHA_TALK_GHOST_FOLLOW = "Fooolooowooomeeee..."
STRINGS.MUSHA_TALK_GHOST_STAY = "Soooootaaaaayyyyyyyee..."
STRINGS.MUSHA_TALK_GHOST_GATHER = "Cooooooooleeecttt..."
STRINGS.MUSHA_TALK_GHOST_STOP = "Stooooooopeeeee..."

STRINGS.MUSHA_TALK_SHIELD_COOL_90 = "[Shield]\nOn Cooldown -[90sec]"
STRINGS.MUSHA_TALK_SHIELD_COOL_80 = "[Shield]\nOn Cooldown -[80sec]"
STRINGS.MUSHA_TALK_SHIELD_COOL_70 = "[Shield]\nOn Cooldown -[70sec]"
STRINGS.MUSHA_TALK_SHIELD_COOL_60 = "[Shield]\nOn Cooldown -[60sec]"
STRINGS.MUSHA_TALK_SHIELD_FULL = "[Shield] is fully charged!"
STRINGS.MUSHA_TALK_TREASURE_FIRST = "What a strange place to hide something."
STRINGS.MUSHA_TALK_TREASURE_YAMCHE = "I knew it smelled something! It's Yamche!"
STRINGS.MUSHA_TALK_TREASURE_FAILED = "Hmm... nothing \n maybe, Musha can try again another time."
STRINGS.MUSHA_TALK_TREASURE_FAR = "The smell comes from very far!"
STRINGS.MUSHA_TALK_TREASURE_MED = "The smell is not that far away from here!"
STRINGS.MUSHA_TALK_TREASURE_NEAR = "Oooh! It's close!"
STRINGS.MUSHA_TALK_TREASURE_SMELL = "*sniff...What's this smell?"
STRINGS.MUSHA_TALK_TREASURE_SNIFF = "Hmm... Smells like treasure."
STRINGS.MUSHA_TALK_TREASURE_FOUND = "[Musha found something!]"
STRINGS.MUSHA_TALK_TREASURE_MARK = "[Marking spot on the map]"

STRINGS.MUSHA_TALK_MUSIC_READY = "Musha is ready to play her Music"
STRINGS.MUSHA_TALK_MUSIC_RIDE = "Musha cannot play her music on the Beefalo"
STRINGS.MUSHA_TALK_MUSIC_TYPE = "Everyone! Look at me playing!\nMusic♪[type]:"

STRINGS.MUSHA_TALK_SLEEP_NO_1 = "The sun is still up"
STRINGS.MUSHA_TALK_SLEEP_NO_2 = "It's still morning"
STRINGS.MUSHA_TALK_SLEEP_NO_3 = "I'ts too bright outside..."
STRINGS.MUSHA_TALK_SLEEP_NO_4 = "Musha needs to stay awake"
STRINGS.MUSHA_TALK_SLEEP_NO_5 = "Sleep?...No..."
STRINGS.MUSHA_TALK_SLEEP_DIZZY_0 = "Musha is so dizzy"
STRINGS.MUSHA_TALK_SLEEP_DIZZY_1 = "Musha feels a bit dizzy"
STRINGS.MUSHA_TALK_SLEEP_DIZZY_2 = "Musha is so tired"
STRINGS.MUSHA_TALK_SLEEP_DIZZY_3 = "Musha could sleep forever"
STRINGS.MUSHA_TALK_SLEEP_DIZZY_4 = "Musha can't see anything, she is so tired"
STRINGS.MUSHA_TALK_SLEEP_DIZZY_5 = "Musha needs to rest"
STRINGS.MUSHA_TALK_SLEEP_DIZZY_6 = "So sleepy..."
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_1 = "It's too dark!"
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_2 = "Musha needs more light!"
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_3 = "The darkness is too dangerous!"
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_4 = "Musha needs to find a lightsource!"
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_5 = "Musha needs fire!"
STRINGS.MUSHA_TALK_SLEEP_GOOD_1 = "Always sleepy ..."
STRINGS.MUSHA_TALK_SLEEP_GOOD_2 = "Sleep tight!"
STRINGS.MUSHA_TALK_SLEEP_GOOD_3 = "make the bed."
STRINGS.MUSHA_TALK_SLEEP_GOOD_4 = "Sweet dreams."
STRINGS.MUSHA_TALK_SLEEP_GOOD = "[Musha can sleep well now]"
STRINGS.MUSHA_TALK_SLEEP_DANGER_1 = "*sniff... Musha smells danger!"
STRINGS.MUSHA_TALK_SLEEP_DANGER_2 = "Somethings wrong, Musha can feel it."
STRINGS.MUSHA_TALK_SLEEP_DANGER_3 = "This is not where Musha will be buried!"
STRINGS.MUSHA_TALK_SLEEP_DANGER_4 = "...Musha heard something..."
STRINGS.MUSHA_TALK_SLEEP_DANGER_5 = "No! Wake up, Musha!"

STRINGS.MUSHA_TALK_SNEAK_UNHIDE = "[Re-appear]"
STRINGS.MUSHA_TALK_SNEAK_NO_TARGET = "Musha can't see a target!"
STRINGS.MUSHA_TALK_SNEAK_SUCCESS = "Backstab was succsesful!"
STRINGS.MUSHA_TALK_SNEAK_FROZEN = "Frozen target: [Half Damage]"
STRINGS.MUSHA_TALK_SNEAK_FAILED = "Backstab has failed!"
STRINGS.MUSHA_TALK_SNEAK_ATTACKED = "The enemies has found Musha!"
STRINGS.MUSHA_TALK_SNEAK_NEED_EXP = "Musha can't hide! \n(Required Level: 5)"
STRINGS.MUSHA_TALK_SNEAK_HIDE = "Hide"
STRINGS.MUSHA_TALK_SNEAK_SHADOW = "Musha is in the shadows!"
--PET
STRINGS.MUSHA_TALK_THIEF_1 = "[Don't touch me...]"
STRINGS.MUSHA_TALK_THIEF_2 = "[Go away!]"
STRINGS.MUSHA_TALK_THIEF_3 = "[Monkey...]"
STRINGS.MUSHA_TALK_THIEF_4 = "[Thief!]"
STRINGS.MUSHA_TALK_FOLLOW = "[I will follow!]"
STRINGS.MUSHA_HEALTH_MAX = "[Max Health]"
STRINGS.MUSHA_TALK_EXP_EXTRA = "Extra [EXP](+1)"
STRINGS.MUSHA_TALK_GROWUP_NEXT = "NEXT:[Level up]"
STRINGS.MUSHA_TALK_GROWUP = "[Level up]"
STRINGS.MUSHA_TALK_YAM_COME = "Come on, Yamche!"
STRINGS.MUSHA_YAMCHE_FOOD = "Foo, food ?"
STRINGS.MUSHA_YAMCHE_FOO = "Foo?"
STRINGS.MUSHA_YAMCHE_FOOOD = "Foo, food !"
STRINGS.MUSHA_YAMCHE_FOOOOD = "Foooood!"
STRINGS.MUSHA_YAMCHE_HEAL = "Kkuu!"
STRINGS.MUSHA_YAMCHE_GREETING_1 = "[Musha!]"
STRINGS.MUSHA_YAMCHE_GREETING_2 = "[I will follow you!]"
STRINGS.MUSHA_YAMCHE_GREETING_3 = "[I'am happy to see you!]"
STRINGS.MUSHA_YAMCHE_GREETING_4 = "[I have missed you, Musha!]"
STRINGS.MUSHA_YAMCHE_GREETING_5 = "[I can see you, Musha!]"
STRINGS.MUSHA_YAMCHE_GREETING_6 = "[Musha, choose me!]"
STRINGS.MUSHA_YAMCHE_GREETING_7 = "[I love you, Musha!]"
STRINGS.MUSHA_YAMCHE_GREETING_8 = "[Let's go!]"
STRINGS.MUSHA_YAMCHE_GREETING_9 = "[I like you, Musha!]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_FOLLOW = "Yamche, follow me!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_STAY = "Yamche, stay away!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SLEEPY = "He seems a bit tired... Let's let him sleep."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_EGG = "He needs to rest more."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LOST = "Musha can't call Yamche..."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_GATHER = "Yamche, collet stuff around us."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_GATHER_STOP = "Yamche, stop collecting."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SHOWME = "Yamche, show me your stuffs."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_DROP = "[Drop All]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_HUNGRY = "Hunger Speed"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_STUFF = "[Gathering Items]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LIGHT = "Light◎[ON]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LIGHT_OFF = "Light◎[OFF]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_WORKING = "[Working]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SLEEP = "[Sleeping...]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SLEEPY = "Sleepy..."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_COST =  "[Health] Cost:"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_COST_HUNGER =  "[Hunger] Cost:-5"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LIGHTNING = "Lightning[ON]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_CAMPFIRE_ON = "Campfire-(ON)"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_CAMPFIRE_OFF = "Campfire-(OFF)"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_FIRE_WARM = "[♨]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_FIRE_COLD = "[※]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_DANGER = "Danger!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_OVEN = "[♨]" 
STRINGS.MUSHA_TALK_ORDER_YAMCHE_FREEZER = "[※]" 
STRINGS.MUSHA_TALK_ORDER_YAMCHE_INV = "[Inventory]" 
STRINGS.MUSHA_TALK_ORDER_YAMCHE_INV_FULL = "[Inventory-Full]"
STRINGS.MUSHA_TALK_YAMCHE_REVIVE_D = "Hee izzzz tooooo yooouung .."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SHIELD_COOL = "[Shield]\nCooldown -[300sec]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_HEALTH_WARN1 = "[Health is below:(20%)!]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_HEALTH_WARN2 = "[health is below:(10%)!]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_REST = "[Rest]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_HUNT = "Yamche, let the hunt begin!!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_OFFENSE = "[Offensive]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_PROTECT = "Yamche, protect Musha!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_DEFFENSE = "[Defensive]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_RETREAT ="Yamche, avoid battle!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_AVOID = "[Avoidance]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_BERSERK = "Back off!, Krrr!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_GHOST = "Yaaaam.. Dooooo nooooot faaaaaieet.."
STRINGS.MUSHA_TALK_ORDER_DALL_FOLLOW = "Dall, follow me!"
STRINGS.MUSHA_TALK_ORDER_DALL_STAY = "Dall, stay here!"
STRINGS.MUSHA_TALK_ORDER_DALL_SLEEPY = "He seems really sleepy..."
STRINGS.MUSHA_TALK_ORDER_DALL_LOST = "Musha can't call Dall..."

STRINGS.MUSHA_TALK_ORDER_ARONG_FOLLOW = "Arong, follow me!"
STRINGS.MUSHA_TALK_ORDER_ARONG_STAY = "Arong, stay away!"
STRINGS.MUSHA_TALK_ORDER_ARONG_SLEEPY = "He needs some rest..."  --can't order
STRINGS.MUSHA_TALK_ORDER_ARONG_LOST = "Musha can't call Arong..."

--bodyguard wilson
STRINGS.MUSHA_TALK_WILSON_DANGER_1 = "Time to battle."
STRINGS.MUSHA_TALK_WILSON_DANGER_2 = "Be careful, Musha!"
STRINGS.MUSHA_TALK_WILSON_DANGER_3 = "Prepare to battle!"
STRINGS.MUSHA_TALK_WILSON_DANGER_4 = "We have to stick together."
STRINGS.MUSHA_TALK_WILSON_DANGER_5 = "Don't worry, Princess!"
STRINGS.MUSHA_TALK_WILSON_DANGER_6 = "Musha, I will protect you."
STRINGS.MUSHA_TALK_WILSON_RANDOM_1 = "Musha! I'm here!!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_2 = "Musha!!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_3 = "Musha! I will help you!!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_4 = "Musha! I heard your voice!!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_5 = "Don't worry, Princess!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_6 = "Musha! I will protect you  !!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_1 = "Wilson!!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_2 = "You saved me!!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_3 = "Thank you!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_4 = "Nice Timing!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_5 = "I missed you!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_6 = "Great!"
STRINGS.MUSHA_TALK_WILSON_BYE_W = "It's time, see you again, Musha..."
STRINGS.MUSHA_TALK_WILSON_BYE_1 = "Thanks, Wilson..."
STRINGS.MUSHA_TALK_WILSON_BYE_2 = "See you again..."
STRINGS.MUSHA_TALK_WILSON_BYE_3 = "Good bye..."
STRINGS.MUSHA_TALK_WILSON_BYE_4 = "Thank you."
STRINGS.MUSHA_TALK_WILSON_FAILED = "Oh no..."

STRINGS.MUSHA_TALK_WILSON_C_R_1	= "I am your blade."
STRINGS.MUSHA_TALK_WILSON_C_R_2	= "After you"
STRINGS.MUSHA_TALK_WILSON_C_R_3	= "I'm so cool"
STRINGS.MUSHA_TALK_WILSON_C_R_4	= "Are we going?"
STRINGS.MUSHA_TALK_WILSON_C_R_5	= "Adventure is waiting for us."
STRINGS.MUSHA_TALK_WILSON_C_R_6	= "Are we stopping?"
STRINGS.MUSHA_TALK_WILSON_C_R_7	= "Interesting..."
STRINGS.MUSHA_TALK_WILSON_C_R_8	= "Call me a Jedi, if you don't mind."
STRINGS.MUSHA_TALK_WILSON_C_R_9	= "What is that? Oh... just a bird..."
STRINGS.MUSHA_TALK_WILSON_C_R_10 = "Great adventure."

STRINGS.MUSHA_TALK_WILSON_C_NIGHT_1 = "Darkness is coming..."
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_2 = "Don't worry, I will stick around you."
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_3 = "Be careful, Musha"
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_4 = "We have to prepare for the darkness."
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_5 = "Good night and good luck."
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_6 = "Night time...\nwe need some sleep."

STRINGS.MUSHA_TALK_WILSON_C_HUNGRY_1 = "I am getting hungry."
STRINGS.MUSHA_TALK_WILSON_C_HUNGRY_2 = "I want something to eat."
STRINGS.MUSHA_TALK_WILSON_C_HUNGRY_3 = "I need to eat some snacks."
STRINGS.MUSHA_TALK_WILSON_C_HUNGRY_4 = "I'm going to go home if I'm starving."

STRINGS.MUSHA_TALK_WILSON_FIGHT_1 = "Die, monster!!"
STRINGS.MUSHA_TALK_WILSON_FIGHT_2 = "Come on!"
STRINGS.MUSHA_TALK_WILSON_FIGHT_3 = "Lightning!!"
STRINGS.MUSHA_TALK_WILSON_FIGHT_4 = "Power of science!"
STRINGS.MUSHA_TALK_WILSON_FIGHT_5 = "See my Power!!"

STRINGS.MUSHA_TALK_WILSON_FULL_1 = "I'm not a glutton."
STRINGS.MUSHA_TALK_WILSON_FULL_1 = "No, thanks."
STRINGS.MUSHA_TALK_WILSON_FULL = "I am full."

--chat1
STRINGS.MUSHA_TALK_WILSON_C1_1 = "I am Cool guy. Right?"
STRINGS.MUSHA_TALK_WILSON_C1_2 = "..."
STRINGS.MUSHA_TALK_WILSON_C1_3 = "Musha, you are a really pretty girl."
STRINGS.MUSHA_TALK_WILSON_C1_4 = "Ok, you are a cool guy."
--chat2
STRINGS.MUSHA_TALK_WILSON_C2_1 = "Musha, you are a really pretty dog."
STRINGS.MUSHA_TALK_WILSON_C2_2 = "Are you hungry?"
--chat3
STRINGS.MUSHA_TALK_WILSON_C3_1 = "What is this smell?"
STRINGS.MUSHA_TALK_WILSON_C3_2 = "...What smell?"
STRINGS.MUSHA_TALK_WILSON_C3_3 = "Sorry, it's just me."
STRINGS.MUSHA_TALK_WILSON_C3_4 = "Musha knew it!"
--chat4
STRINGS.MUSHA_TALK_WILSON_C4_1 = "Just a moment."
STRINGS.MUSHA_TALK_WILSON_C4_2 = "Why?"
STRINGS.MUSHA_TALK_WILSON_C4_3 = "..."
--chat5
STRINGS.MUSHA_TALK_WILSON_C5_1 = "Musha, are we resting here?"
STRINGS.MUSHA_TALK_WILSON_C5_2 = "No, we have to keep going!"
STRINGS.MUSHA_TALK_WILSON_C5_3 = "Yeah... we have to rest."
--chat6
STRINGS.MUSHA_TALK_WILSON_C6_1 = "Musha, can I buy your Yamche?"
STRINGS.MUSHA_TALK_WILSON_C6_2 = "Yamche is a friend."
STRINGS.MUSHA_TALK_WILSON_C6_3 = "Well, you can buy me, if you want to."
STRINGS.MUSHA_TALK_WILSON_C6_4 = "Ehm... i'll pass."
--chat7
STRINGS.MUSHA_TALK_WILSON_C7_1 = "Musha, how can I get the Phoenix?"
STRINGS.MUSHA_TALK_WILSON_C7_2 = "Try digging dirt with a shovel."
STRINGS.MUSHA_TALK_WILSON_C7_3 = "You are kidding, right?"
--chat8
STRINGS.MUSHA_TALK_WILSON_C8_1 = "You are so beautiful. Will you merry me?"
STRINGS.MUSHA_TALK_WILSON_C8_2 = "NO!"
--chat9
STRINGS.MUSHA_TALK_WILSON_C9_1 = "A Dog a Bird and a Genius."
STRINGS.MUSHA_TALK_WILSON_C9_2 = "Who is the Genius?"
STRINGS.MUSHA_TALK_WILSON_C9_3 = "...of course you are."
STRINGS.MUSHA_TALK_WILSON_C9_4 = "You are an excellent survivor."

STRINGS.MUSHA_TALK_HUNGRY = "So hungry..."
STRINGS.MUSHA_TALK_BERSERK = "...Feel my power..."
STRINGS.MUSHA_TALK_KILL_EPIC = "[Kill Epic Monster]"
STRINGS.MUSHA_TALK_KILL_GIANT = "[Kill Giant]"
STRINGS.MUSHA_TALK_COFFEE_1 = "This is coffee!"
STRINGS.MUSHA_TALK_COFFEE_2 = "Smells so good!"
STRINGS.MUSHA_TALK_COFFEE_3 = "Wonderful!"
STRINGS.MUSHA_TALK_FOOD_EXP = "Yam Yam !!\n [EXP] + 25"
STRINGS.MUSHA_TALK_FOOD_BAD_1 = "It tastes bad!"
STRINGS.MUSHA_TALK_FOOD_BAD_2 = "Ew! It tastes horrible!"
STRINGS.MUSHA_TALK_FOOD_BAD_3 = "It left a nasty taste in my mouth."
STRINGS.MUSHA_TALK_FOOD_BAD_4 = "This food doesn't suit my taste..."
STRINGS.MUSHA_TALK_FOOD_BAD_MEAT = "Musha doesn't likes the taste of meat..."
STRINGS.MUSHA_TALK_FOOD_BAD_VEGGIE = "Musha doesn't likes the taste of vegetables..."
STRINGS.MUSHA_TALK_FOOD_OLD_1 = "Ew! I can smell it! It smells horrible!"
STRINGS.MUSHA_TALK_FOOD_OLD_2 = "This food is too old for Musha!"
STRINGS.MUSHA_TALK_FOOD_OLD_3 = "It's not fresh food..."
STRINGS.MUSHA_TALK_FOOD_BUG_1 = "It's a BUG!"
STRINGS.MUSHA_TALK_FOOD_BUG_2 = "It left a nasty taste in my mouth."
STRINGS.MUSHA_TALK_FOOD_BUG_3 = "Why did musha ate a bug?"
STRINGS.MUSHA_TALK_FOOD_MONSTER_1 = "Monster meat doesn't suit my taste..."
STRINGS.MUSHA_TALK_FOOD_MONSTER_2 = "Musha doesn't likes the taste of monster meat..."
STRINGS.MUSHA_TALK_FOOD_VEGE = "...can even eat a vegetable."
STRINGS.MUSHA_TALK_FOOD_MEAT = "...can even eat a meat."

STRINGS.MUSHA_TALK_FORGE_ON = "[Forge]-(ON)"
STRINGS.MUSHA_TALK_FORGE_OFF = "[Forge]-(OFF)"

STRINGS.MUSHA_TALK_CANNOT1 = "Musha can't do it right now."
STRINGS.MUSHA_TALK_CANNOT2 = "Musha can't do it right now.\n[Frost Tentacle]:Limited Summoned"
--Items
STRINGS.MUSHA_TALK_FORGE_LUCKY = "[ Forge -Lucky Points★ x5]"
STRINGS.MUSHA_ITEM_GROWPOINTS = "GP☆"
STRINGS.MUSHA_ITEM_LUCKY = "Lucky Points★"
STRINGS.MUSHA_ITEM_DUR = "Durability"
STRINGS.MUSHA_ITEM_LIGHT = "Light◎"
STRINGS.MUSHA_ITEM_SPEED = "Speed: UP▲"
STRINGS.MUSHA_ITEM_SPEED_DOWN = "Speed: DOWN▼"
STRINGS.MUSHA_ITEM_REGEN = "Regenerate♥"
STRINGS.MUSHA_ITEM_SANITY_REGEN = "Sanity Regen♤"
STRINGS.MUSHA_ITEM_WARMNCOOL = "♣Warm/Cool◇"
STRINGS.MUSHA_ITEM_WARM = "Warm♣"
STRINGS.MUSHA_ITEM_COOL = "Cool◇"
STRINGS.MUSHA_ITEM_FREEZE = "Freeze※"
STRINGS.MUSHA_ITEM_SHIELD = "[Shield:On]"
STRINGS.MUSHA_ITEM_SHIELD_BROKEN = "[Shield:Broken]"

STRINGS.MUSHA_UPGRADE = "UPGRADE"
STRINGS.MUSHA_WEAPON = "[Weapon]"
STRINGS.MUSHA_WEAPON_DAMAGE = "Damage"
STRINGS.MUSHA_WEAPON_FIRE = "Flame◀"
STRINGS.MUSHA_WEAPON_DARK = "Dark Flame◀"
STRINGS.MUSHA_WEAPON_FIRE_D = "Flame Damage◀"
STRINGS.MUSHA_WEAPON_FROST = "Frost※"
STRINGS.MUSHA_WEAPON_BLINK = "Blink◈"
STRINGS.MUSHA_WEAPON_BLOOD = "Blood Poison⊙"
STRINGS.MUSHA_WEAPON_POISON = "Poison⊙"
STRINGS.MUSHA_WEAPON_SANITY = "Sanity Vampire♠"
STRINGS.MUSHA_WEAPON_FROST_RELEASE = "[Release Frost]"
STRINGS.MUSHA_WEAPON_FROST_PRESERVED = "[Preserve Frost]"
STRINGS.MUSHA_WEAPON_AREA = "Area Attack▣"
STRINGS.MUSHA_WEAPON_FROZENSHARD = "Frozen Shard※"
STRINGS.MUSHA_WEAPON_TENTACLE_FROST = "Frost Tentacle"
STRINGS.MUSHA_WEAPON_WINTERCOST = "Winter(No-Cost)"
STRINGS.MUSHA_WEAPON_COOLER = "Cooler◇ (Cost)"
STRINGS.MUSHA_WEAPON_FREEZESLOW = "Freeze/Slow※"

STRINGS.MUSHA_HAT_BROKEN = "Hat: Broken"
STRINGS.MUSHA_HAT_BROKEN_C = "Crown: Broken"
STRINGS.MUSHA_HAT_PRINCESS = "Princess Crown"
STRINGS.MUSHA_HAT_QUEEN = "Queen Crown"
STRINGS.MUSHA_HAT_BUNNY = "Bunny Scout"
STRINGS.MUSHA_HAT_BUNNYA = "Iron Bunny"
STRINGS.MUSHA_HAT_CAT = "Iron Cat"
STRINGS.MUSHA_HAT_PHOENIX = "Phoenix Helmet"

STRINGS.MUSHA_ARMOR = "Armor"
STRINGS.MUSHA_ARMOR_BROKEN = "Armor: Broken"
STRINGS.MUSHA_ARMOR_MUSHAA = "Musha's Armor"
STRINGS.MUSHA_ARMOR_MUSHAB = "Princess Armor"
STRINGS.MUSHA_ARMOR_FROST = "Frost Armor"
STRINGS.MUSHA_ARMOR_PIRATE = "Pirate Chest"

STRINGS.MUSHA_WEAPON_BROKEN = "Weapon: Broken"
STRINGS.MUSHA_WEAPON_BROKEN_TALK = "It's broken!"
STRINGS.MUSHA_WEAPON_SWORD_BASE = "Blade: Broken"
STRINGS.MUSHA_WEAPON_SWORD_BASE_UP = "Prototype Blade"
STRINGS.MUSHA_WEAPON_SWORD_FIRE = "Phoenix Blade"
STRINGS.MUSHA_WEAPON_SWORD_FROST = "Frost Blade"
STRINGS.MUSHA_WEAPON_SWORD_AXE = "Phoenix Axe"
STRINGS.MUSHA_WEAPON_SWORD_PAXE = "Phoenix Pickaxe"
STRINGS.MUSHA_WEAPON_SWORD_SPEAR = "Phoenix Glaive"
STRINGS.MUSHA_WEAPON_SPEAR_FIRE = "Fire Glaive "
STRINGS.MUSHA_WEAPON_SPEAR_FROST = "Frost Glaive "
STRINGS.MUSHA_WEAPON_SWORD_BOW = "Blade-Bow"
STRINGS.MUSHA_WEAPON_FROSTHAMMER = "Frost Hammer"
STRINGS.MUSHA_WEAPON_BB_VIPER = "Viper"
STRINGS.MUSHA_WEAPON_BB_BOW = "Sunny"
STRINGS.MUSHA_WEAPON_BB_ARROWS = "-No more Arrows-"
STRINGS.MUSHA_WEAPON_SWORD_POWER_1 = "[Power Blade I]"
STRINGS.MUSHA_WEAPON_SWORD_POWER_2 = "[Power Blade II]"
STRINGS.MUSHA_WEAPON_SWORD_POWER_3 = "[Power Blade III]"
STRINGS.MUSHA_WEAPON_SWORD_POWER_OFF = "Power Off"

--description

STRINGS.NAMES.PIRATEBACK = "Pirate Chest"
STRINGS.RECIPE_PIRATEBACK = "Dead Man's Chest"
STRINGS.RECIPE_DESC.PIRATEBACK = "Dead Man's Chest\n - Davy Jones -"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEBACK = "Musha would never put her hearth in a chest."

STRINGS.NAMES.MUSHA_OVEN = "Frog Oven"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_OVEN = "It looks like a frog!"
STRINGS.RECIPE_MUSHA_OVEN = "Frog Oven"
STRINGS.RECIPE_DESC.MUSHA_OVEN = "Warm or Cold\nOven or Fridge"

STRINGS.NAMES.TENT_MUSHA = "Musha's Tent"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TENT_MUSHA = "Home, Sweet Home"
STRINGS.RECIPE_TENT_MUSHA = "Leaves Tent"
STRINGS.RECIPE_DESC.TENT_MUSHA = "Tent, Light source"

STRINGS.NAMES.FORGE_MUSHA = "Musha's Forge"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FORGE_MUSHA = "Let's upgrade\n Musha's items!"
STRINGS.RECIPE_FORGE_MUSHAA = "Upgrade Forge"
STRINGS.RECIPE_DESC.FORGE_MUSHA = "Forge, Light source,\n Fridge"

STRINGS.NAMES.MUSHA_HUT = "Grass Hut"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_HUT = "It's comfortable!"
STRINGS.MUSHA_HUT = "Grass Hut"
STRINGS.RECIPE_DESC.MUSHA_HUT = "Shelter from the rain"

STRINGS.NAMES.GREEN_APPLE_PLANT = "Sagua Plant"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREEN_APPLE_PLANT = "Smells nice!"
STRINGS.NAMES.GREEN_FRUIT = "Caffeine Apple"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREEN_FRUIT = "This, is really good!"
STRINGS.NAMES.GREEN_FRUIT_COOKED = "Cream Apple"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREEN_FRUIT_COOKED = "Fantastic!"
STRINGS.NAMES.GREENWORM = "Sagua Monster"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREENWORM = "Smells bad!"
STRINGS.NAMES.GWORM = "Green Monster"
STRINGS.NAMES.GWORM_PLANT = "Sagua Plant"
STRINGS.NAMES.GWORM_DIRT = "Dirt"
STRINGS.NAMES.TUNACAN = "Tuna"
STRINGS.RECIPE_DESC.TUNACAN = "Canned food, Tuna content:0.001%"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNACAN = "Canned fish!"
STRINGS.NAMES.TUNACAN_MUSHA = "Tuna"
STRINGS.RECIPE_DESC.TUNACAN_MUSHA = "Canned food, Tuna content:0.001%"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNACAN_MUSHA = "Canned fish!"

STRINGS.NAMES.MUSHA_EGG_RANDOM = "Super baby Egg"
STRINGS.NAMES.MUSHA_EGG_RANDOM_CRACKED = "Super baby Egg"
STRINGS.NAMES.MUSHA_EGG_ARONG = "Fluffy Egg"
STRINGS.NAMES.MUSHA_EGG_CRACKED_ARONG = "Fluffy Egg"
STRINGS.NAMES.MUSHA_EGG = "Phoenix Egg"
STRINGS.NAMES.MUSHA_EGG_CRACKED = "Phoenix Egg"
STRINGS.NAMES.MUSHA_EGGS1 = "Phoenix Egg(LV 2)"
STRINGS.NAMES.MUSHA_EGG_CRACKEDS1 = "Phoenix Egg"
STRINGS.NAMES.MUSHA_EGGS2 = "Phoenix Egg(LV 3)"
STRINGS.NAMES.MUSHA_EGG_CRACKEDS2 = "Phoenix Egg"
STRINGS.NAMES.MUSHA_EGGS3 = "Phoenix Egg(LV 4)"
STRINGS.NAMES.MUSHA_EGG_CRACKEDS3 = "Phoenix Egg"
STRINGS.NAMES.MUSHA_EGG1 = "Phoenix Egg(LV 5)"
STRINGS.NAMES.MUSHA_EGG_CRACKED1 = "Phoenix Egg"
STRINGS.NAMES.MUSHA_EGG2 = "Phoenix Egg(LV 6)"
STRINGS.NAMES.MUSHA_EGG_CRACKED2 = "Phoenix Egg"
STRINGS.NAMES.MUSHA_EGG3 = "Phoenix Egg(LV 7)"
STRINGS.NAMES.MUSHA_EGG_CRACKED3 = "Phoenix Egg"
STRINGS.NAMES.MUSHA_EGG8 = "Phoenix Egg(LV 8)"
STRINGS.NAMES.MUSHA_EGG_CRACKED8 = "Phoenix Egg"
STRINGS.NAMES.MUSHA_EGG = "Phoenix Egg"

STRINGS.NAMES.MUSHA_SPORE_FIRE = "Fire Wisp"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_SPORE_FIRE = "It'll be warm in the winter."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_ARONG = "Fur Egg"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_RANDOM = "Super baby Yamche Egg"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG = "Phoenix Egg"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGGS1 = "Phoenix Egg(LV 2)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGGS2 = "Phoenix Egg(LV 3)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGGS3 = "Phoenix Egg(LV 4)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG1 = "Phoenix Egg(LV 5)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG2 = "Phoenix Egg(LV 6)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG3 = "Phoenix Egg(LV 7)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG8 = "Phoenix Egg(LV 8)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED = "It's not Musha's. Musha said that is Yamche's bud."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKEDS1 = "It's not Musha's. Musha said that is Yamche's bud."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKEDS2 = "It's not Musha's. Musha said that is Yamche's bud."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKEDS3 = "It's not Musha's. Musha said that is Yamche's bud."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED1 = "It's not Musha's. Musha said that is Yamche's bud."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED2 = "It's not Musha's. Musha said that is Yamche's bud."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED3 = "It's not Musha's. Musha said that is Yamche's bud."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED8 = "It's not Musha's. Musha said that is Yamche's bud."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARONG_BABY = "Grow up! My buddy!\nCommand:(F1)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARONG = "The fastest Beefalo in the world!\nCommand:(F1)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AROM = "The fastest girl in the world!\nCommand:(F1)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONTREE = "He is 'Dall na mu'.\nIt means, The  Moon Tree in an ancient word.\nCommand:(F2)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONNUTDRAKE = "The Ent king's servant"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONNUTDRAKE2 = "Where are they coming from?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONLIGHT_PLANT = "Pretty colors! But, tastes bad."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_SMALL = "What a cute little bird!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_SMALL_SUPER = "What a cute little bird!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEEN = "He can not sleep on my head... \nbut he still so cute."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENR1 = "He can not sleep on my head... \nbut he still so cute."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENR2 = "He can not sleep on my head... \nbut he still so cute."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENR3 = "He can not sleep on my head... \nbut he still so cute."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENR4 = "He can not sleep on my head... \nbut he still so cute."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENICE = "He can not sleep on my head... \nbut he still so cute."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL = "Yamche eats anything. So glad."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLR1 = "Yamche eats anything. So glad."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLR2 = "Yamche eats anything. So glad."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLR3 = "Yamche eats anything. So glad."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLR4 = "Yamche eats anything. So glad."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRICE = "Yamche eats anything. So glad."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL2 = "How useful bird it is!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR1 = "How useful bird it is!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR2 = "How useful bird it is!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR3 = "How useful bird it is!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR4 = "How useful bird it is!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR5 = "How useful bird it is!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRICE = "How useful bird it is!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL3 = "Yamche is not just a bird. He is a friend of Musha."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR1 = "Yamche is not just a bird. He is a friend of Musha."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR2 = "Yamche is not just a bird. He is a friend of Musha."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR3 = "Yamche is not just a bird. He is a friend of Musha."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR4 = "Yamche is not just a bird. He is a friend of Musha."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR5 = "Yamche is not just a bird. He is a friend of Musha."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRICE = "Yamche is not just a bird. He is a friend of Musha."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL4 = "Yes. I agree. We are family."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR1 = "Yes. I agree. We are family."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR2 = "Yes. I agree. We are family."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR3 = "Yes. I agree. We are family."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR4 = "Yes. I agree. We are family."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR5 = "Yes. I agree. We are family."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR6 = "Yes. I agree. We are family."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRICE = "Yes. I agree. We are family."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL5 = "Travelling together. It's the best."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR1 = "Travelling together. It's the best."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR2 = "Travelling together. It's the best."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR3 = "Travelling together. It's the best."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR4 = "Travelling together. It's the best."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR5 = "Travelling together. It's the best."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR6 = "Travelling together. It's the best."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRRICE = "Travelling together. It's the best."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP1 = "Don't starve partner."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP2 = "Don't starve partner."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP3 = "Don't starve partner."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP4 = "Don't starve partner."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP5 = "Don't starve partner."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP6 = "Don't starve partner."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP7 = "Don't starve partner."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RPICE = "Don't starve partner."
STRINGS.NAMES.GHOSTHOUND = "Ghost Hound"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GHOSTHOUND = "Musha summoned an ancient ghost!"
STRINGS.NAMES.GHOSTHOUND2 = "Ghost Puppy"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GHOSTHOUND2 = "Purified Puppy Soul"
STRINGS.NAMES.SHADOWMUSHA = "Musha's Shadow"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOWMUSHA = "That shadow looks like Musha."
STRINGS.NAMES.TENTACLE_FROST = "Frozen tentacle"
STRINGS.NAMES.TENTACLE_SHADOW = "Shadow tentacle"

STRINGS.RECIPE_DESC.MUSHA_EGG = "Companion Yamche\n(Order keys:'Z,V,B')"
STRINGS.RECIPE_DESC.MUSHA_EGG_ARONG = "Companion Arong\n(Order key:'F1')"
STRINGS.RECIPE_DESC.MUSHA_EGG_RANDOM = "Powerful but eternal baby."
STRINGS.RECIPE_DESC.MOONTREE = "Companion Dall\n (Order key:'F2')"
STRINGS.NAMES.MOONTREE = "Tree of the Moon"
STRINGS.RECIPE_DESC.MUSHA_EGGS1 = "Phoenix Egg (Lv.2)"
STRINGS.RECIPE_DESC.MUSHA_EGGS2 = "Phoenix Egg (Lv.3)"
STRINGS.RECIPE_DESC.MUSHA_EGGS3 = "Phoenix Egg (Lv.4)"
STRINGS.RECIPE_DESC.MUSHA_EGG1 = "Phoenix Egg (Lv.5)"
STRINGS.RECIPE_DESC.MUSHA_EGG2 = "Phoenix Egg (Lv.6)"
STRINGS.RECIPE_DESC.MUSHA_EGG3 = "Phoenix Egg (Lv.7)"
STRINGS.RECIPE_DESC.MUSHA_EGG8 = "Phoenix Egg (Lv.Max)"
STRINGS.RECIPE_DESC.REDGEM = "Alchemical recipe for:\nRed Gem"
STRINGS.RECIPE_DESC.BLUEGEM = "Alchemical recipe for:\nBlue Gem" 
STRINGS.RECIPE_DESC.GREENGEM = "Alchemical recipe for:\nGreen Gem" 
STRINGS.RECIPE_DESC.YELLOWGEM = "Alchemical recipe for:\nYellow Gem" 
STRINGS.RECIPE_DESC.ORANGEGEM = "Alchemical recipe for:\nOrange Gem" 

STRINGS.NAMES.MOONNUTDRAKE = "Kkobong"
STRINGS.NAMES.MOONNUTDRAKE2 = "Booha"
STRINGS.NAMES.MOONBUSH = "Berry Bush"
STRINGS.NAMES.MOONLIGHT_PLANT = "Glowberry tree"

STRINGS.NAMES.REDGEM = "Red Gem"
STRINGS.NAMES.BLUEGEM = "Blue Gem" 
STRINGS.NAMES.GREENGEM = "Green Gem" 
STRINGS.NAMES.YELLOWGEM = "Yellow Gem" 
STRINGS.NAMES.ORANGEGEM = "Orange Gem" 

STRINGS.NAMES.MUSHASWORD_BASE = "Broken Blade"
STRINGS.NAMES.MUSHASWORD = "Phoenix Blade"
STRINGS.NAMES.MUSHASWORD4 = "Phoenix Axe"
STRINGS.NAMES.MUSHASWORD_FROST = "Frost Phoenix Blade"
STRINGS.RECIPE_DESC.MUSHASWORD_BASE = "Broken Phoenix Blade"
STRINGS.RECIPE_DESC.MUSHASWORD = "Upgradeable Weapon\nChanges visually"
STRINGS.RECIPE_DESC.MUSHASWORD4 = "Upgradeable Weapon\nAxe"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TREASURE = "Musha has found you!"
STRINGS.NAMES.MUSHA_TREASURE = "Treasure"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ASSASIN_WILSON = "Wilson?"
STRINGS.NAMES.ASSASIN_WILSON = "Wilsoon"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TREASURE2 = "Musha has found you!"
STRINGS.NAMES.MUSHA_TREASURE2 = "Strange place to hide something."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_HIDDEN_EGG = "Come out, Yamche!"
STRINGS.NAMES.MUSHA_HIDDEN_EGG = "Strange place to hide something."

STRINGS.RECIPE_DESC.MUSHASWORD_FROST = "Upgradeable Weapon\nChanges visually"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHASWORD_BASE = "Can be fixed with the elementals."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHASWORD = "Can be fixed with the elementals. I'ts a fire sword"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHASWORD_FROST = "Can be fixed with the elementals. I'ts a frost sword"
STRINGS.NAMES.MUSHA_FLUTE = "Musha's Flute"
STRINGS.RECIPE_DESC.MUSHA_FLUTE = "Healing Music♪.\nRepair: Glowdust, Light bulb"
STRINGS.NAMES.GLOWDUST = "Glowdust"
STRINGS.RECIPE_DESC.GLOWDUST = "Dust of the light.\nDelicious."

STRINGS.RECIPE_DESC.WORMLIGHT_LESSER = "Alchemical recipe for:\nGlowberry"
STRINGS.NAMES.PORTION_E = "Energy Drink"
STRINGS.RECIPE_DESC.PORTION_E = "Energy Drink"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTION_E = "Let me see...\n[Contains Caffein Apple:99%]"
STRINGS.NAMES.CRISTAL = "Crystal Candy"
STRINGS.RECIPE_DESC.CRISTAL = "summon apple tree\ncan change Yamche's color"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRISTAL = "Musha can change the color of Yamchae with this."
STRINGS.NAMES.EXP = "Energy Essence"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EXP = "It gives some EXP to the player."
STRINGS.NAMES.EXP1000CHEAT = "Cheat Essence"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EXP1000CHEAT = "It gives a ton of EXP to the player."
STRINGS.NAMES.FROSTHAMMER = "Frost Hammer"
STRINGS.RECIPE_DESC.FROSTHAMMER = "Upgradeable Weapon Area attack:(Right click)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROSTHAMMER = "Heavy, big, blue friend."
STRINGS.NAMES.BROKEN_FROSTHAMMER = "Frost Armor"
STRINGS.RECIPE_DESC.BROKEN_FROSTHAMMER = "Upgradeable Armor, Compact, Fridge"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BROKEN_FROSTHAMMER =  "It has multiple functions."
STRINGS.NAMES.PHOENIXSPEAR = "Phoenix Glaive"
STRINGS.RECIPE_DESC.PHOENIXSPEAR = "Upgradeable Weapon Long Blade, Shovel"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PHOENIXSPEAR = "It's a long weapon, but it's very light!"
STRINGS.NAMES.BOWM = "Blade-Bow"
STRINGS.RECIPE_DESC.BOWM = "Upgradeable Weapon\nBow:(Right click)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOWM = "Sorry Viper. Musha loves Sunny more than you."
STRINGS.NAMES.ARROWM = "Arrow"
STRINGS.RECIPE_DESC.ARROWM = "Basic Arrow"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARROWM = "Hello, pointy boy!"
STRINGS.NAMES.ARROWM_BROKEN = "Broken Arrow"
STRINGS.RECIPE_DESC.ARROWM_BROKEN = "Broken Arrow"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARROWM_BROKEN = "Musha can fix this."
STRINGS.NAMES.DUMMY_ARROW0 = "Arrow"
STRINGS.RECIPE_DESC.DUMMY_ARROW0 = "Basic Arrow x2"
STRINGS.NAMES.DUMMY_ARROW1 = "Arrow"
STRINGS.RECIPE_DESC.DUMMY_ARROW1 = "Basic Arrow x2"
STRINGS.NAMES.DUMMY_ARROW2 = "Arrow"
STRINGS.RECIPE_DESC.DUMMY_ARROW2 = "Basic Arrow x2"
STRINGS.NAMES.DUMMY_ARROW3 = "Arrow"
STRINGS.RECIPE_DESC.DUMMY_ARROW3 = "Basic Arrow x2"
STRINGS.NAMES.DUMMY_ARROW4 = "Arrow"
STRINGS.RECIPE_DESC.DUMMY_ARROW4 = "Basic Arrow x6"
STRINGS.NAMES.HAT_MPHOENIX = "Phoenix Helmet"
STRINGS.RECIPE_DESC.HAT_MPHOENIX = "Upgradeable Armor\nMask:(Right click)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MPHOENIX = "A medieval helm."
STRINGS.NAMES.HAT_MPRINCESS = "Puppy Princess Crown"
STRINGS.RECIPE_DESC.HAT_MPRINCESS = "Shield, Sanity regen\nChanges visually"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MPRINCESS = "A golden little crown."
STRINGS.NAMES.HAT_MCROWN = "Puppy Queen Crown"
STRINGS.RECIPE_DESC.HAT_MCROWN = "Shield, Sanity Regen\nSpecial Ability"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MCROWN = "Looks so nice."
STRINGS.NAMES.HAT_MBUNNY = "Bunny Scout Hat"
STRINGS.RECIPE_DESC.HAT_MBUNNY = "Upgradeable Armor Goggles:(Right click)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MBUNNY = "It has bunny ears!"
STRINGS.NAMES.HAT_MBUNNYA = "Iron Bunny Helmet"
STRINGS.RECIPE_DESC.HAT_MBUNNYA = "Upgradeable Armor Light, Goggles:(Right click)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MBUNNYA = "Super Heroine: Iron Bunny!"
STRINGS.NAMES.HAT_MWILDCAT = "Iron Cat Helmet"
STRINGS.RECIPE_DESC.HAT_MWILDCAT = "Upgradeable Armor\nLight:(Right click)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MWILDCAT = "Super Hero: Iron Cat!"
STRINGS.NAMES.ARMOR_MUSHAA = "Musha's Armor"
STRINGS.RECIPE_DESC.ARMOR_MUSHAA = "Upgradeable Armor Compact, Backpack"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_MUSHAA = "It's a billow dress."
STRINGS.NAMES.ARMOR_MUSHAB = "Princess Armor"
STRINGS.RECIPE_DESC.ARMOR_MUSHAB = "Upgradeable Armor Backpack, Warm and Cool"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_MUSHAB = "It's billow, but safer." 
-----------------random -name
STRINGS.PHOENIXS=
{    
"Captain Yamche","Hulk Yamche","Iron Yamche","Torr Yamche","Yamche","Brave Yamche","Cutie Yamche","Owl Yamche","Sunny Yamche","Moon Yamche","Seoul Yamche","Suri Yamche","Vilja Yamche","Sunny Yamche","Sunnyholic","Musha Yamche","Mellisa Yamche","Lidia Yamche ","Battleborn Yamche ","Grey Yamche","Sky Yamche","Lucia Yamche","Khajit Yamche","Pig Yamche","Mjoll Yamche","Lioness Yamche","Muiri Yamche","Ysolda Yamche","Rayya Yamche","Falkas Yamche","Vilkas Yamche","Aela Yamche","Huter Yamche","Huntress Yamche","Queen Yamche","Fire Yamche","Cicero Yamche","Top Yamche","Lina Yamche","Totoro Yamche","Yu-na Yamche","Winter Yamche","White Yamche","Mellisa Yamche","Riften Yamche","Dawnstar Yamche","Windhelm Yamche","Pho Yamche","Sneaky Yamche","Kiwis Yamche","Coco Yamche","Moon Yamche","Pizza Yamche","Sugar Yamche","Orc Yamche","Elf Yamche","Knight Yamche","Vlad Yamche","Azeroth Yamche","Tauren Yamche","Troll Yamche","Thrall Yamche","Narugar Yamche","Yancook Yamche","Tirano Yamche","Honey Yamche","Golum Yamche","Bosom Yamche","Esmeralda Yamche","Pluvia Yamche","Doraemon Yamche","Dooly Yamche","Apple Yamche","IU Yamche","Gandalf Yamche","Frodo Yamche","Sam Yamche","Regolas Yamche","Gimli Yamche","Boromir Yamche","Wilxon Yamche","Willo Yamche","Wolfkong Yamche","Wenil Yamche","WX79 Yamche","Wickerbi Yamche","Woorie Yamche","Wex Yamche","Maximus Yamche","Wigfreedom Yamche","Webbers Yamche","Naruto Yamche","Sasuke Yamche","Witcher Yamche","Luka Yamche","Arong Yamche","Puppy Yamche",
 }
STRINGS.ARONG=
{    
"Captain Arong","Hulk Arong","Iron Arong","Torr Arong","Yamche","Brave Arong","Cutie Arong","Owl Arong","Sunny Arong","Moon Arong","Seoul Arong","Suri Arong","Vilja Arong","Sunny Arong","Sunnyholic","Musha Arong","Mellisa Arong","Lidia Arong ","Battleborn Arong ","Grey Arong","Sky Arong","Lucia Arong","Khajit Arong","Pig Arong","Mjoll Arong","Lioness Arong","Muiri Arong","Ysolda Arong","Rayya Arong","Falkas Arong","Vilkas Arong","Aela Arong","Huter Arong","Huntress Arong","Queen Arong","Fire Arong","Cicero Arong","Top Arong","Lina Arong","Totoro Arong","Yu-na Arong","Winter Arong","White Arong","Mellisa Arong","Riften Arong","Dawnstar Arong","Windhelm Arong","Pho Arong","Sneaky Arong","Kiwis Arong","Coco Arong","Moon Arong","Pizza Arong","Sugar Arong","Orc Arong","Elf Arong","Knight Arong","Vlad Arong","Azeroth Arong","Tauren Arong","Troll Arong","Thrall Arong","Narugar Arong","Yancook Arong","Tirano Arong","Honey Arong","Golum Arong","Bosom Arong","Esmeralda Arong","Pluvia Arong","Doraemon Arong","Dooly Arong","Apple Arong","IU Arong","Gandalf Arong","Frodo Arong","Sam Arong","Regolas Arong","Gimli Arong","Boromir Arong","Wilxon Arong","Willo Arong","Wolfkong Arong","Wenil Arong","WX79 Arong","Wickerbi Arong","Woorie Arong","Wex Arong","Maximus Arong","Wigfreedom Arong","Webbers Arong","Naruto Arong","Sasuke Arong","Witcher Arong","Luka Arong","Arong Arong","Puppy Arong",
 }
 STRINGS.AROM=
{    
"Captain Arom","Hulk Arom","Iron Arom","Torr Arom","Yamche","Brave Arom","Cutie Arom","Owl Arom","Sunny Arom","Moon Arom","Seoul Arom","Suri Arom","Vilja Arom","Sunny Arom","Sunnyholic","Musha Arom","Mellisa Arom","Lidia Arom ","Battleborn Arom ","Grey Arom","Sky Arom","Lucia Arom","Khajit Arom","Pig Arom","Mjoll Arom","Lioness Arom","Muiri Arom","Ysolda Arom","Rayya Arom","Falkas Arom","Vilkas Arom","Aela Arom","Huter Arom","Huntress Arom","Queen Arom","Fire Arom","Cicero Arom","Top Arom","Lina Arom","Totoro Arom","Yu-na Arom","Winter Arom","White Arom","Mellisa Arom","Riften Arom","Dawnstar Arom","Windhelm Arom","Pho Arom","Sneaky Arom","Kiwis Arom","Coco Arom","Moon Arom","Pizza Arom","Sugar Arom","Orc Arom","Elf Arom","Knight Arom","Vlad Arom","Azeroth Arom","Tauren Arom","Troll Arom","Thrall Arom","Narugar Arom","Yancook Arom","Tirano Arom","Honey Arom","Golum Arom","Bosom Arom","Esmeralda Arom","Pluvia Arom","Doraemon Arom","Dooly Arom","Apple Arom","IU Arom","Gandalf Arom","Frodo Arom","Sam Arom","Regolas Arom","Gimli Arom","Boromir Arom","Wilxon Arom","Willo Arom","Wolfkong Arom","Wenil Arom","WX79 Arom","Wickerbi Arom","Woorie Arom","Wex Arom","Maximus Arom","Wigfreedom Arom","Webbers Arom","Naruto Arom","Sasuke Arom","Witcher Arom","Luka Arom","Arong Arom","Puppy Arom",
 }
STRINGS.DALL=
{    
"Captain Dall","Hulk Dall","Iron Dall","Torr Dall","Yamche","Brave Dall","Cutie Dall","Owl Dall","Sunny Dall","Moon Dall","Seoul Dall","Suri Dall","Vilja Dall","Sunny Dall","Sunnyholic","Musha Dall","Mellisa Dall","Lidia Dall ","Battleborn Dall ","Grey Dall","Sky Dall","Lucia Dall","Khajit Dall","Pig Dall","Mjoll Dall","Lioness Dall","Muiri Dall","Ysolda Dall","Rayya Dall","Falkas Dall","Vilkas Dall","Aela Dall","Huter Dall","Huntress Dall","Queen Dall","Fire Dall","Cicero Dall","Top Dall","Lina Dall","Totoro Dall","Yu-na Dall","Winter Dall","White Dall","Mellisa Dall","Riften Dall","Dawnstar Dall","Windhelm Dall","Pho Dall","Sneaky Dall","Kiwis Dall","Coco Dall","Moon Dall","Pizza Dall","Sugar Dall","Orc Dall","Elf Dall","Knight Dall","Vlad Dall","Azeroth Dall","Tauren Dall","Troll Dall","Thrall Dall","Narugar Dall","Yancook Dall","Tirano Dall","Honey Dall","Golum Dall","Bosom Dall","Esmeralda Dall","Pluvia Dall","Doraemon Dall","Dooly Dall","Apple Dall","IU Dall","Gandalf Dall","Frodo Dall","Sam Dall","Regolas Dall","Gimli Dall","Boromir Dall","Wilxon Dall","Willo Dall","Wolfkong Dall","Wenil Dall","WX79 Dall","Wickerbi Dall","Woorie Dall","Wex Dall","Maximus Dall","Wigfreedom Dall","Webbers Dall","Naruto Dall","Sasuke Dall","Witcher Dall","Luka Dall","Arong Dall","Puppy Dall",
 }
 --adds
STRINGS.MUSHA_YAMCHE = "[Yamche]"
STRINGS.MUSHA_HEALTH_HUNGER = "Health/Hunger"
STRINGS.MUSHA_HEALTH = "Health"
STRINGS.MUSHA_HUNGER = "Hunger" 
STRINGS.MUSHA_TALK_ORDER_PET_FOLLOW = "Come with me"
STRINGS.MUSHA_TALK_ORDER_PET_STAY = "Stay here."
STRINGS.MUSHA_TALK_ORDER_PET_LOST = "Musha can't see her pet!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LEVEL1 = "He is too young."
STRINGS.MUSHA_TALK_NEED_SPELLPOWER = "Not enough [Mana]"
STRINGS.MUSHA_MYPOWER_CALL_LIGHTNING = "Lightning Call"
STRINGS.MUSHA_MYPOWER_SMITE = "Smite"

STRINGS.MUSHA_ACTION_REPAIR = "Repair"
STRINGS.MUSHA_ACTION_ADDFUEL = "Add Fuel"