STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.MUSHA = "Муша"
STRINGS.CHARACTER_TITLES.musha = "Принцесса щенок Муша [DST]"
STRINGS.CHARACTER_NAMES.musha = "Муша"
STRINGS.CHARACTER_DESCRIPTIONS.musha = "[Расти и открывай навыки]\nСтатус(L) Навык(K) Форма(P)\nВалькирия(R) Тень(G) Щит(C) Музыка(X) Сон(T) Ямши(Z,V,B))"
STRINGS.CHARACTER_QUOTES.musha = " Я настоящая принцесса! "

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSHA = ("Может она присоединится к моему книжному клубу.")
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MUSHA = ("Королевская кровь? Хм...")
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MUSHA = ("Он может трансформироваться?..нет, наверное нет.")
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MUSHA = ("Она слабая... Но может помочь нам.")
STRINGS.CHARACTERS.WENDY.DESCRIBE.MUSHA = ("Я чувствую сильный дух.")
STRINGS.CHARACTERS.WX78.DESCRIBE.MUSHA = ("Я слышу свое сердце.")
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA = 
{
GENERIC = "Чувствую себя здорово!",
ATTACKER = "Бой Бой Бой",
MURDERER = "Убийца!",
REVIVER = "Возврат...",
GHOST = "Держись подальше!",
}

--status
STRINGS.MUSHA_LEVEL_NEXT_LEVEL_UP = "Следующий уровень"
STRINGS.MUSHA_LEVEL_LEVEL = "Уровень"
STRINGS.MUSHA_LEVEL_EXP = "[Опыт]"
STRINGS.MUSHA_LEVEL_SLEEP = "Сон"
STRINGS.MUSHA_LEVEL_TIRED = "Усталось"
STRINGS.MUSHA_LEVEL_MUSIC = "Музыка"
STRINGS.MUSHA_LEVEL_SNIFF = "Нюх"
STRINGS.MUSHA_SLEEP_TIRED = "[Сон / Усталось]"
STRINGS.MUSHA_VISUAL_BASE = "[Основная форма]"
STRINGS.MUSHA_BADGE_SLEEP = "[Значок сна]"
STRINGS.MUSHA_YAMCHE_DEBUG = "[Настройка]\nВыбросить все"
STRINGS.MUSHA_MUSIC_DYNAMIC = "[Динамичная музыка]\n:Случайно"
STRINGS.MUSHA_MUSIC_DYNAMIC_OFF = "[Динамичная музыка]\n:Выкл"
STRINGS.MUSHA_DEATH_PENALTY = "[Смерть]\n[Опыт]"

STRINGS.MUSHA_SKILL_ACTIVE  = "[------Активный навык------]"
STRINGS.MUSHA_SKILL_SLEEP   = "Спать / Проснуться   "
STRINGS.MUSHA_SKILL_POWER   = "Сила Молнии "
STRINGS.MUSHA_SKILL_SHIELD  = "Искрящийся Щит	   "
STRINGS.MUSHA_SKILL_MUSIC   = "Музыка             "
STRINGS.MUSHA_SKILL_SHADOW  = "Спрятаться в тени  "
STRINGS.MUSHA_SKILL_PASSIVE = "[------Пассивный навык------] "
STRINGS.MUSHA_SKILL_VALKYR  = "Валькирия       "
STRINGS.MUSHA_SKILL_BERSERK = "Берсерк         "
STRINGS.MUSHA_SKILL_ELECTRA = "Электрический Щит "
STRINGS.MUSHA_SKILL_CRITIC  = "Критический Удар    "
STRINGS.MUSHA_SKILL_DOUBLE  = "Двойной Урон "
STRINGS.MUSHA_T_SKILL_UNLOCK = "Открыть: "
STRINGS.MUSHA_T_SKILL_VALKYRIE = "Валькирия"
STRINGS.MUSHA_T_SKILL_V_LIGHTNING = "Авто Молния"
STRINGS.MUSHA_T_SKILL_V_POWER = "Мощная Молния"
STRINGS.MUSHA_T_SKILL_V_ARMOR = "Броня Валькирии"
STRINGS.MUSHA_T_SKILL_V_LIGHTNING = "Молния Валькирии"
STRINGS.MUSHA_T_SKILL_UP_ACTIVE = "Апгрейд [Активные Навыки]"
STRINGS.MUSHA_T_SKILL_CRITICAL = "Критический Удар"
STRINGS.MUSHA_T_SKILL_E_SHIELD = "Электрический Щит"
STRINGS.MUSHA_T_SKILL_BERSERK = "Берсерк"
STRINGS.MUSHA_T_SKILL_B_ARMOR = "Броня Берсерка"
STRINGS.MUSHA_T_SKILL_DOUBLE = "Двойной Урон"

--TALK
STRINGS.MUSHA_TALK_READY_POISON = "Ядовитая атака готова!"
STRINGS.MUSHA_TALK_CANCEL_POISON = "Муша передумала..."
STRINGS.MUSHA_TALK_NEED_SANITY = "Нужно больше [Разума]..."
STRINGS.MUSHA_TALK_NEED_SLEEPY = "Муша не может сконцентрироваться. Слишком устала..."
STRINGS.MUSHA_TALK_NEED_SLEEP = "Муше нужно больше спать!"
STRINGS.MUSHA_TALK_NEED_EXP = "Нужно больше опыта!"

STRINGS.MUSHA_TALK_GRRR = "Гррр....!"
STRINGS.MUSHA_TALK_GHOST_REVENGE = "Оооох! Меееееессссссть!!"
STRINGS.MUSHA_TALK_GHOST_OOOOHHHH = "Оооооххххх!!"
STRINGS.MUSHA_TALK_GHOST_OOOOH = "Ооооох......"
STRINGS.MUSHA_TALK_GHOST_MUSIC = "Оооох~ Охоооох~"
STRINGS.MUSHA_TALK_GHOST_SLEEP = " .. Спааааааать .. "
STRINGS.MUSHA_TALK_GHOST_FOLLOW = "Слеееедуууууйзамнооооой..."
STRINGS.MUSHA_TALK_GHOST_STAY = "Стооооооойтуууууут..."
STRINGS.MUSHA_TALK_GHOST_GATHER = "Сооообииииирааааай..."
STRINGS.MUSHA_TALK_GHOST_STOP = "Стооооооооййййй"

STRINGS.MUSHA_TALK_SHIELD_COOL_90 = "[Щит] откат -[90сек]"
STRINGS.MUSHA_TALK_SHIELD_COOL_80 = "[Щит] откат -[80сек]"
STRINGS.MUSHA_TALK_SHIELD_COOL_70 = "[Щит] откат -[70сек]"
STRINGS.MUSHA_TALK_SHIELD_COOL_60 = "[Щит] откат -[60сек]"
STRINGS.MUSHA_TALK_SHIELD_FULL = "Полностью заряжен [Щит]"
STRINGS.MUSHA_TALK_TREASURE_FIRST = "Странное место !!"
STRINGS.MUSHA_TALK_TREASURE_YAMCHE = "Муша чует запах цветочной птички."
STRINGS.MUSHA_TALK_TREASURE_FAILED = "Ничего.. \n Может попробывать снова позже..."
STRINGS.MUSHA_TALK_TREASURE_FAR = "Запах доносится из далека..."
STRINGS.MUSHA_TALK_TREASURE_MED = "Пахнет не так далеко."
STRINGS.MUSHA_TALK_TREASURE_NEAR = "Оно близко!!"
STRINGS.MUSHA_TALK_TREASURE_SMELL = "Это это за запах??"
STRINGS.MUSHA_TALK_TREASURE_SNIFF = "Может это запах сокровищ..."
STRINGS.MUSHA_TALK_TREASURE_FOUND = "[Муша что-то нашла!]"
STRINGS.MUSHA_TALK_TREASURE_MARK = "[Сделаю пометку на карте...]"

STRINGS.MUSHA_TALK_MUSIC_READY = "Муша готова к [спектаклю]"
STRINGS.MUSHA_TALK_MUSIC_RIDE = "Муша не может играть на бифало.."
STRINGS.MUSHA_TALK_MUSIC_TYPE = "Посмотри на меня!\nМузыка-[тип]: "

STRINGS.MUSHA_TALK_SLEEP_NO_1 = "Привет солнышко?"
STRINGS.MUSHA_TALK_SLEEP_NO_2 = "Доброе утро?"
STRINGS.MUSHA_TALK_SLEEP_NO_3 = "Слишком ярко..."
STRINGS.MUSHA_TALK_SLEEP_NO_4 = "Проснись Муша."
STRINGS.MUSHA_TALK_SLEEP_NO_5 = "Спать? Нет..."
STRINGS.MUSHA_TALK_SLEEP_DIZZY_0 = "Голова кружится..."
STRINGS.MUSHA_TALK_SLEEP_DIZZY_1 = "Немного шатает."
STRINGS.MUSHA_TALK_SLEEP_DIZZY_2 = "Так устала..."
STRINGS.MUSHA_TALK_SLEEP_DIZZY_3 = "Муша очень хочет спать..."
STRINGS.MUSHA_TALK_SLEEP_DIZZY_4 = "Ничего не вижу..."
STRINGS.MUSHA_TALK_SLEEP_DIZZY_5 = "Муше надо отдохнуть..."
STRINGS.MUSHA_TALK_SLEEP_DIZZY_6 = "Спааа..."
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_1 = "Слишком темно..."
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_2 = "Больше света!"
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_3 = "Темнота слишком опасна..."
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_4 = "Муше надо найти огонь!"
STRINGS.MUSHA_TALK_SLEEP_NEED_LIGHT_5 = "Муже нужен огонь!"
STRINGS.MUSHA_TALK_SLEEP_GOOD_1 = "Всегда сонный ..."
STRINGS.MUSHA_TALK_SLEEP_GOOD_2 = "нравится тепло.."
STRINGS.MUSHA_TALK_SLEEP_GOOD_3 = "сделайте кровать."
STRINGS.MUSHA_TALK_SLEEP_GOOD_4 = "Сладкие Мечты."
STRINGS.MUSHA_TALK_SLEEP_GOOD = "[Доброго Сна]"
STRINGS.MUSHA_TALK_SLEEP_DANGER_1 = "Пахнет чем-то опасным."
STRINGS.MUSHA_TALK_SLEEP_DANGER_2 = "Муша чует что-то не так..."
STRINGS.MUSHA_TALK_SLEEP_DANGER_3 = "Это место не мой дом."
STRINGS.MUSHA_TALK_SLEEP_DANGER_4 = "...Что-то слышится..."
STRINGS.MUSHA_TALK_SLEEP_DANGER_5 = "Нет! Проснись!"

STRINGS.MUSHA_TALK_SNEAK_UNHIDE = "Покажись!"
STRINGS.MUSHA_TALK_SNEAK_NO_TARGET = "Это не противник."
STRINGS.MUSHA_TALK_SNEAK_SUCCESS = "Успешный Удар!"
STRINGS.MUSHA_TALK_SNEAK_FROZEN = "Заморозка : [Половина Урона]"
STRINGS.MUSHA_TALK_SNEAK_FAILED = "Неудачный Удар..."
STRINGS.MUSHA_TALK_SNEAK_ATTACKED = "Враги нашли меня!"
STRINGS.MUSHA_TALK_SNEAK_NEED_EXP = "Муша не может [Скрыться]...\n(Нужный уровень: 5)"
STRINGS.MUSHA_TALK_SNEAK_HIDE = "Скрыться"
STRINGS.MUSHA_TALK_SNEAK_SHADOW = "Муша - Тень!"
--PET
STRINGS.MUSHA_TALK_THIEF_1 = "[Не трогай меня..]"
STRINGS.MUSHA_TALK_THIEF_2 = "[Держись подальше!]"
STRINGS.MUSHA_TALK_THIEF_3 = "[Обезьяны...]"
STRINGS.MUSHA_TALK_THIEF_4 = "[Вор!]"
STRINGS.MUSHA_TALK_FOLLOW = "[Мне нравится следовать...]"
STRINGS.MUSHA_HEALTH_MAX = "[Максимальное здоровье]"
STRINGS.MUSHA_TALK_EXP_EXTRA = "Экстра [Опыт](+1)"
STRINGS.MUSHA_TALK_GROWUP_NEXT = "Далее:[Взросление]"
STRINGS.MUSHA_TALK_GROWUP = "[Взросление]"
STRINGS.MUSHA_TALK_YAM_COME = "Давай, Ямши!"
STRINGS.MUSHA_YAMCHE_FOOD = "Пиии Пиища?"
STRINGS.MUSHA_YAMCHE_FOO = "Пиии?"
STRINGS.MUSHA_YAMCHE_FOOOD = "Пии Едаа!"
STRINGS.MUSHA_YAMCHE_FOOOOD = "Едаааааа!"
STRINGS.MUSHA_YAMCHE_HEAL = "Ккууу"
STRINGS.MUSHA_YAMCHE_GREETING_1 = "[Муша!]"
STRINGS.MUSHA_YAMCHE_GREETING_2 = "[Я пойду за тобой]"
STRINGS.MUSHA_YAMCHE_GREETING_3 = "[Счастье]"
STRINGS.MUSHA_YAMCHE_GREETING_4 = "[Я скучаю без тебя]"
STRINGS.MUSHA_YAMCHE_GREETING_5 = "[Я тебя вижу]"
STRINGS.MUSHA_YAMCHE_GREETING_6 = "[Муша меня выбрала]"
STRINGS.MUSHA_YAMCHE_GREETING_7 = "[Я люблю Мушу]"
STRINGS.MUSHA_YAMCHE_GREETING_8 = "[Вперед Вперед]"
STRINGS.MUSHA_YAMCHE_GREETING_9 = "[Ты мне нравишься]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_FOLLOW = "Ямши, Следуй за мной!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_STAY = "Ямши, стой на месте"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SLEEPY = "Похоже он очень устал..."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_EGG = "Ему нужно больше отдыха..."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LOST = "Муша не может позвать Ямши..."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_GATHER = "Ямши, подбирай вещи."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_GATHER_STOP = "Прекрати подбирать."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SHOWME = "Ямши, покажи свои вещи."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_DROP = "[Выкинь все]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_HUNGRY = "Голодная скорость"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_STUFF = "[Подобранные вещи]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LIGHT = "Свет[ВКЛ]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LIGHT_OFF = "Свет[ВЫКЛ]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_WORKING = "[Работает...]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SLEEP = "[Спит...]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SLEEPY = "Сонный..."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_COST =  "[Здоровье] Расход:"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_COST_HUNGER =  "[Голод] Расход:-5"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LIGHTNING = "Молния[ВКЛ]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_CAMPFIRE_ON = "Костер-(ВКЛ)"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_CAMPFIRE_OFF = "Костер-(ВЫКЛ)"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_FIRE_WARM = "[♨]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_FIRE_COLD = "[※]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_DANGER = "Опасность!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_OVEN = "[♨]" 
STRINGS.MUSHA_TALK_ORDER_YAMCHE_FREEZER = "[※]" 
STRINGS.MUSHA_TALK_ORDER_YAMCHE_INV = "[Инвентарь]" 
STRINGS.MUSHA_TALK_ORDER_YAMCHE_INV_FULL = "[Инвентарь полон]"
STRINGS.MUSHA_TALK_YAMCHE_REVIVE_D = "Оон слиииишком молодоооой.."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_SHIELD_COOL = "[Щит]\nОткат -[300сек]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_HEALTH_WARN1 = "[Здоровье: меньше (20%)]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_HEALTH_WARN2 = "[Здоровье: меньше (10%)]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_REST = "[Отдых]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_HUNT = "Ямши, начинай охоту!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_OFFENSE = "[Атака]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_PROTECT = "Ямши, защищай меня!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_DEFFENSE = "[Защита]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_RETREAT ="Ямши, избегай битвы!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_AVOID = "[Уклонение]"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_BERSERK = "Назад!, Кррр!"
STRINGS.MUSHA_TALK_ORDER_YAMCHE_GHOST = "Яааааам.. Нееееее сражааайсяяяяя..."
STRINGS.MUSHA_TALK_ORDER_DALL_FOLLOW = "Далл, следуй за мной!"
STRINGS.MUSHA_TALK_ORDER_DALL_STAY = "Далл, стой тут."
STRINGS.MUSHA_TALK_ORDER_DALL_SLEEPY = "Он выглядит сонным..."
STRINGS.MUSHA_TALK_ORDER_DALL_LOST = "Муша не может позвать Далла."

STRINGS.MUSHA_TALK_ORDER_ARONG_FOLLOW = "Аронг, следуй за мной!"
STRINGS.MUSHA_TALK_ORDER_ARONG_STAY = "Аронг, стой тут."
STRINGS.MUSHA_TALK_ORDER_ARONG_SLEEPY = "Ему нужно отдохнуть..."
STRINGS.MUSHA_TALK_ORDER_ARONG_LOST = "Муша не может позвать Аронга."

--bodyguard wilson
STRINGS.MUSHA_TALK_WILSON_DANGER_1 = "Время сражаться."
STRINGS.MUSHA_TALK_WILSON_DANGER_2 = "Осторожнее Муша."
STRINGS.MUSHA_TALK_WILSON_DANGER_3 = "Приготовься к битве!"
STRINGS.MUSHA_TALK_WILSON_DANGER_4 = "Надо держаться вместе."
STRINGS.MUSHA_TALK_WILSON_DANGER_5 = "Не волнуйся Принцесса!"
STRINGS.MUSHA_TALK_WILSON_DANGER_6 = "Муша, я защищу тебя."
STRINGS.MUSHA_TALK_WILSON_RANDOM_1 = "Муша! Я здесь!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_2 = "Муша!!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_3 = "Муша! Я помогу тебе!!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_4 = "Муша! Я слышу твой голос!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_5 = "Не волнуйся принцесса!"
STRINGS.MUSHA_TALK_WILSON_RANDOM_6 = "Муша! Я защищу тебя!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_1 = "Вилсон!!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_2 = "Ты спас меня!!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_3 = "Спасибо тебе!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_4 = "Очень вовремя!"
STRINGS.MUSHA_TALK_WILSON_MUSHA_5 = "Я скучала без тебя."
STRINGS.MUSHA_TALK_WILSON_MUSHA_6 = "Отлично!"
STRINGS.MUSHA_TALK_WILSON_BYE_W = "Время пришло, увидимся снова, Муша..."
STRINGS.MUSHA_TALK_WILSON_BYE_1 = "Спасибо Вилсон..."
STRINGS.MUSHA_TALK_WILSON_BYE_2 = "Увидимся..."
STRINGS.MUSHA_TALK_WILSON_BYE_3 = "Прощай..."
STRINGS.MUSHA_TALK_WILSON_BYE_4 = "Спасибо тебе..."
STRINGS.MUSHA_TALK_WILSON_FAILED = "Ох нет..."

STRINGS.MUSHA_TALK_WILSON_C_R_1	= "Я твой клинок."
STRINGS.MUSHA_TALK_WILSON_C_R_2	= "Я за тобой."
STRINGS.MUSHA_TALK_WILSON_C_R_3	= "Я такой клевый."
STRINGS.MUSHA_TALK_WILSON_C_R_4	= "Идем?"
STRINGS.MUSHA_TALK_WILSON_C_R_5	= "Приключения ждут нас."
STRINGS.MUSHA_TALK_WILSON_C_R_6	= "Мы остановились?"
STRINGS.MUSHA_TALK_WILSON_C_R_7	= "Интересно..."
STRINGS.MUSHA_TALK_WILSON_C_R_8	= "Зови меня Джеди, если хочешь."
STRINGS.MUSHA_TALK_WILSON_C_R_9	= "Что это? Ох... просто птица."
STRINGS.MUSHA_TALK_WILSON_C_R_10 = "Отличное приключение."

STRINGS.MUSHA_TALK_WILSON_C_NIGHT_1 = "Темнота приближается..."
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_2 = "Не волнуйся, я буду рядом с тобой."
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_3 = "Будь осторожна Муша."
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_4 = "Нам нужно приготовиться к темноте."
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_5 = "Доброй ночи и удачи."
STRINGS.MUSHA_TALK_WILSON_C_NIGHT_6 = "Ночное время...\nНам нужно поспать."

STRINGS.MUSHA_TALK_WILSON_C_HUNGRY_1 = "Я проголодался."
STRINGS.MUSHA_TALK_WILSON_C_HUNGRY_2 = "Я хочу что-нибудь съесть."
STRINGS.MUSHA_TALK_WILSON_C_HUNGRY_3 = "Мне нужна еда."
STRINGS.MUSHA_TALK_WILSON_C_HUNGRY_4 = "Я отправлюсь домой если буду голодать."

STRINGS.MUSHA_TALK_WILSON_FIGHT_1 = "Умри Монстр!"
STRINGS.MUSHA_TALK_WILSON_FIGHT_2 = "Давай!"
STRINGS.MUSHA_TALK_WILSON_FIGHT_3 = "Молния!!"
STRINGS.MUSHA_TALK_WILSON_FIGHT_4 = "Сила науки!"
STRINGS.MUSHA_TALK_WILSON_FIGHT_5 = "Узри мою Мощь!!"

STRINGS.MUSHA_TALK_WILSON_FULL_1 = "Я не свинтус."
STRINGS.MUSHA_TALK_WILSON_FULL_1 = "Нет, спасибо."
STRINGS.MUSHA_TALK_WILSON_FULL = "Я сыт."

--chat1
STRINGS.MUSHA_TALK_WILSON_C1_1 = "Я прикольный парень, правда?"
STRINGS.MUSHA_TALK_WILSON_C1_2 = "..."
STRINGS.MUSHA_TALK_WILSON_C1_3 = "Муша, ты правда очень красивая."
STRINGS.MUSHA_TALK_WILSON_C1_4 = "Ты очень симпатичная."
--chat2
STRINGS.MUSHA_TALK_WILSON_C2_1 = "Муша, ты хорошая собачка."
STRINGS.MUSHA_TALK_WILSON_C2_2 = "Хочешь кушать?"
--chat3
STRINGS.MUSHA_TALK_WILSON_C3_1 = "Что это за запах?"
STRINGS.MUSHA_TALK_WILSON_C3_2 = "...Чем пахнет?"
STRINGS.MUSHA_TALK_WILSON_C3_3 = "Извини, это я."
STRINGS.MUSHA_TALK_WILSON_C3_4 = "Муша знает это."
--chat4
STRINGS.MUSHA_TALK_WILSON_C4_1 = "Один момент."
STRINGS.MUSHA_TALK_WILSON_C4_2 = "Почему?"
STRINGS.MUSHA_TALK_WILSON_C4_3 = "..."
--chat5
STRINGS.MUSHA_TALK_WILSON_C5_1 = "Муша, мы отдохнем тут?"
STRINGS.MUSHA_TALK_WILSON_C5_2 = "Нет, нам нужно идти."
STRINGS.MUSHA_TALK_WILSON_C5_3 = "Да... нам надо отдохнуть."
--chat6
STRINGS.MUSHA_TALK_WILSON_C6_1 = "Муша, можно купить твоего Ямши?"
STRINGS.MUSHA_TALK_WILSON_C6_2 = "Ямши это друг."
STRINGS.MUSHA_TALK_WILSON_C6_3 = "Ну, ты продашь его мне? Если захочешь?"
STRINGS.MUSHA_TALK_WILSON_C6_4 = "Ты не хочешь..."
--chat7
STRINGS.MUSHA_TALK_WILSON_C7_1 = "Муша, как мне получить Феникса?"
STRINGS.MUSHA_TALK_WILSON_C7_2 = "Попробывать копать землю лопатой."
STRINGS.MUSHA_TALK_WILSON_C7_3 = "Ты шутишь да? Это ведь не серьезно?"
--chat8
STRINGS.MUSHA_TALK_WILSON_C8_1 = "Ты такой милый щенок, выходи за меня?"
STRINGS.MUSHA_TALK_WILSON_C8_2 = "НЕТ."
--chat9
STRINGS.MUSHA_TALK_WILSON_C9_1 = "Собака, Птица и Гений."
STRINGS.MUSHA_TALK_WILSON_C9_2 = "Кто тут Гений?"
STRINGS.MUSHA_TALK_WILSON_C9_3 = "...Конечно ты."
STRINGS.MUSHA_TALK_WILSON_C9_4 = "Ты отличный выживальщик."

STRINGS.MUSHA_TALK_HUNGRY = "Так голодно."
STRINGS.MUSHA_TALK_BERSERK = "...Почувствуй мою силу..."
STRINGS.MUSHA_TALK_KILL_EPIC = "[ Убийство Эпического Монстра ]"
STRINGS.MUSHA_TALK_KILL_GIANT = "[ Убийство Гиганта ]"
STRINGS.MUSHA_TALK_COFFEE_1 = "Это кофе!"
STRINGS.MUSHA_TALK_COFFEE_2 = "Пахнет так хорошо!"
STRINGS.MUSHA_TALK_COFFEE_3 = "Прекрасно!"
STRINGS.MUSHA_TALK_FOOD_EXP = "Ам Ам!!\n [Опыт] + 25"
STRINGS.MUSHA_TALK_FOOD_BAD_1 = "Плохой вкус!"
STRINGS.MUSHA_TALK_FOOD_BAD_2 = "Ужасный вкус!"
STRINGS.MUSHA_TALK_FOOD_BAD_3 = "От него во рту ужасный привкус!"
STRINGS.MUSHA_TALK_FOOD_BAD_4 = "Эта еда мне не по вкусу."
STRINGS.MUSHA_TALK_FOOD_BAD_MEAT = "Муше не нравится вкус этого мяса..."
STRINGS.MUSHA_TALK_FOOD_BAD_VEGGIE = "Муше не нравится вкус этого овоща..."
STRINGS.MUSHA_TALK_FOOD_OLD_1 = "...не могу это нюхать!"
STRINGS.MUSHA_TALK_FOOD_OLD_2 = "Слишком старая еда..."
STRINGS.MUSHA_TALK_FOOD_OLD_3 = "Оно не свежее..."
STRINGS.MUSHA_TALK_FOOD_BUG_1 = "Там насекомые!"
STRINGS.MUSHA_TALK_FOOD_BUG_2 = "От него во рту ужасный привкус!"
STRINGS.MUSHA_TALK_FOOD_BUG_3 = "Почему Муша ест жуков?"
STRINGS.MUSHA_TALK_FOOD_MONSTER_1 = "Мясо монстра мне не по вкусу..."
STRINGS.MUSHA_TALK_FOOD_MONSTER_2 = "Муше не нравится мясо монстров..."
STRINGS.MUSHA_TALK_FOOD_VEGE = "... Можно даже есть овощи."
STRINGS.MUSHA_TALK_FOOD_MEAT = "... Можно даже есть мясо."

STRINGS.MUSHA_TALK_FORGE_ON = "[Кузница]-(Вкл)"
STRINGS.MUSHA_TALK_FORGE_OFF = "[Кузница]-(Выкл)"

STRINGS.MUSHA_TALK_CANNOT1 = "Муша не может это сделать сейчас."
STRINGS.MUSHA_TALK_CANNOT2 = "Муша не может это сделать сейчас.\n[Ледяные Щупальца]:Максимальное количество"
--Items
STRINGS.MUSHA_TALK_FORGE_LUCKY = "[ Кузня -Очки Удачи★ x5]"
STRINGS.MUSHA_ITEM_GROWPOINTS = "Очки Роста☆"
STRINGS.MUSHA_ITEM_LUCKY = "Очки Удачи★"
STRINGS.MUSHA_ITEM_DUR = "Прочность"
STRINGS.MUSHA_ITEM_LIGHT = "Свет◎"
STRINGS.MUSHA_ITEM_SPEED = "Скорость выше▲"
STRINGS.MUSHA_ITEM_SPEED_DOWN = "Скорость ниже▼"
STRINGS.MUSHA_ITEM_REGEN = "Восстановление♥"
STRINGS.MUSHA_ITEM_SANITY_REGEN = "Восполнение рассудка♤"
STRINGS.MUSHA_ITEM_WARMNCOOL = "♣Тепло - Холодно◇"
STRINGS.MUSHA_ITEM_WARM = "Тепло♣"
STRINGS.MUSHA_ITEM_COOL = "Холодно◇"
STRINGS.MUSHA_ITEM_FREEZE = "Морозно※"
STRINGS.MUSHA_ITEM_SHIELD = "[Щит Вкл]"
STRINGS.MUSHA_ITEM_SHIELD_BROKEN = "[Щит Сломан]"

STRINGS.MUSHA_UPGRADE = "АПГРЕЙД"
STRINGS.MUSHA_WEAPON = "[Оружие]"
STRINGS.MUSHA_WEAPON_DAMAGE = "Урон"
STRINGS.MUSHA_WEAPON_FIRE = "Пламя◀"
STRINGS.MUSHA_WEAPON_DARK = "Темное пламя◀"
STRINGS.MUSHA_WEAPON_FIRE_D = "Урон Пламенем◀"
STRINGS.MUSHA_WEAPON_FROST = "Мороз※"
STRINGS.MUSHA_WEAPON_BLINK = "Мерцание◈"
STRINGS.MUSHA_WEAPON_BLOOD = "Кровный Яд⊙"
STRINGS.MUSHA_WEAPON_POISON = "Отрава⊙"
STRINGS.MUSHA_WEAPON_SANITY = "Поглощение Рассудка♠"
STRINGS.MUSHA_WEAPON_FROST_RELEASE = "[ Выпустить Мороз ]"
STRINGS.MUSHA_WEAPON_FROST_PRESERVED = "[ Сохранить Мороз ]"
STRINGS.MUSHA_WEAPON_AREA = "Атака по области▣"
STRINGS.MUSHA_WEAPON_FROZENSHARD = "Морозный Осколок※"
STRINGS.MUSHA_WEAPON_TENTACLE_FROST = "Ледяное Щупальце"
STRINGS.MUSHA_WEAPON_WINTERCOST = "Зима(свободно)"
STRINGS.MUSHA_WEAPON_COOLER = "Охлаждение◇ (Цена)"
STRINGS.MUSHA_WEAPON_FREEZESLOW = "Заморозка и Замедление※"

STRINGS.MUSHA_HAT_BROKEN = "Сломанная шляпа"
STRINGS.MUSHA_HAT_BROKEN_C = "Сломанная Корона"
STRINGS.MUSHA_HAT_PRINCESS = "Корона Принцессы"
STRINGS.MUSHA_HAT_QUEEN = "Корона Королевы"
STRINGS.MUSHA_HAT_BUNNY = "Заячий Шлем"
STRINGS.MUSHA_HAT_BUNNYA = "Стальной Кролик"
STRINGS.MUSHA_HAT_CAT = "Стальной Кот"
STRINGS.MUSHA_HAT_PHOENIX = "Шлем Феникса"

STRINGS.MUSHA_ARMOR = "Броня"
STRINGS.MUSHA_ARMOR_BROKEN = "Сломанная Броня"
STRINGS.MUSHA_ARMOR_MUSHAA = "Мушина Броня"
STRINGS.MUSHA_ARMOR_MUSHAB = "Броня Принцессы"
STRINGS.MUSHA_ARMOR_FROST = "Морозная Броня"
STRINGS.MUSHA_ARMOR_PIRATE = "Пиратский Сундук"

STRINGS.MUSHA_WEAPON_BROKEN = "Сломанное Оружие"
STRINGS.MUSHA_WEAPON_BROKEN_TALK = "Он сломан!"
STRINGS.MUSHA_WEAPON_SWORD_BASE = "Сломанное Лезвие"
STRINGS.MUSHA_WEAPON_SWORD_BASE_UP = "Прототип лезвия"
STRINGS.MUSHA_WEAPON_SWORD_FIRE = "Клинок Феникса"
STRINGS.MUSHA_WEAPON_SWORD_FROST = "Ледяной Клинок"
STRINGS.MUSHA_WEAPON_SWORD_AXE = "Секира Феникса"
STRINGS.MUSHA_WEAPON_SWORD_PAXE = "Кирка Феникса"
STRINGS.MUSHA_WEAPON_SWORD_SPEAR = "Копье Феникса"
STRINGS.MUSHA_WEAPON_SPEAR_FIRE = "Огненное Копье"
STRINGS.MUSHA_WEAPON_SPEAR_FROST = "Ледяное Копье"
STRINGS.MUSHA_WEAPON_SWORD_BOW = "Клинок-Лук"
STRINGS.MUSHA_WEAPON_FROSTHAMMER = "Морозный Молот"
STRINGS.MUSHA_WEAPON_BB_VIPER = "Гадюка"
STRINGS.MUSHA_WEAPON_BB_BOW = "Солнышко"
STRINGS.MUSHA_WEAPON_BB_ARROWS = "- Нет Стрел -"
STRINGS.MUSHA_WEAPON_SWORD_POWER_1 = "[ Сильный Клинок I ]"
STRINGS.MUSHA_WEAPON_SWORD_POWER_2 = "[ Сильный Клинок II ]"
STRINGS.MUSHA_WEAPON_SWORD_POWER_3 = "[ Сильный Клинок III ]"
STRINGS.MUSHA_WEAPON_SWORD_POWER_OFF = "Сила Выкл"

--description

STRINGS.NAMES.PIRATEBACK = "Пиратский Сундук"
STRINGS.RECIPE_PIRATEBACK = "Сундук Мертвеца"
STRINGS.RECIPE_DESC.PIRATEBACK = "Сундук Мертвеца\n - Дэви Джонс -"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATEBACK = "Ну... Муша никогда не положит свое сердце в сундук."

STRINGS.NAMES.MUSHA_OVEN = "Жабья Печь"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_OVEN = "Похоже на лягушку!"
STRINGS.RECIPE_MUSHA_OVEN = "Жабья Печь"
STRINGS.RECIPE_DESC.MUSHA_OVEN = "Тепло или Холодно\nДуховка или холодильник"

STRINGS.NAMES.TENT_MUSHA = "Тент Муши"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TENT_MUSHA = "Дом, милый дом"
STRINGS.RECIPE_TENT_MUSHA = "Лиственный тент"
STRINGS.RECIPE_DESC.TENT_MUSHA = "Тент, фонарик"

STRINGS.NAMES.FORGE_MUSHA = "Мушина Кузница"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FORGE_MUSHA = "Давай улучшать вещи!"
STRINGS.RECIPE_FORGE_MUSHAA = "Кузница улучшений"
STRINGS.RECIPE_DESC.FORGE_MUSHA = "Кузница, фонарь, холодильник"

STRINGS.NAMES.MUSHA_HUT = "Травяная Хижина"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_HUT = "В ней комфортно!"
STRINGS.MUSHA_HUT = "Травяная Хижина"
STRINGS.RECIPE_DESC.MUSHA_HUT = "Защита от дождя"

STRINGS.NAMES.GREEN_APPLE_PLANT = "Растение Сага"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREEN_APPLE_PLANT = "Пахнет Хорошо"
STRINGS.NAMES.GREEN_FRUIT = "Кофейное Яблоко"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREEN_FRUIT = "Они правда хороши!"
STRINGS.NAMES.GREEN_FRUIT_COOKED = "Кремовое Яблоко"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREEN_FRUIT_COOKED = "Фантастика!"
STRINGS.NAMES.GREENWORM = "Монстр Сага"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREENWORM = "Плохо пахнет..."
STRINGS.NAMES.GWORM = "Зеленый Монстр"
STRINGS.NAMES.GWORM_PLANT = "Растение Сага"
STRINGS.NAMES.GWORM_DIRT = "Земля"
STRINGS.NAMES.TUNACAN = "Тунец"
STRINGS.RECIPE_DESC.TUNACAN = "Консервированная еда, Содержание тунца: 0.001%"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNACAN = "Стальная Рыба!"
STRINGS.NAMES.TUNACAN_MUSHA = "Тунец"
STRINGS.RECIPE_DESC.TUNACAN_MUSHA = "Консервированная еда, Содержание тунца: 0.001%"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TUNACAN_MUSHA = "Стальная Рыба!"

STRINGS.NAMES.MUSHA_EGG_RANDOM = "Super baby Egg"
STRINGS.NAMES.MUSHA_EGG_RANDOM_CRACKED = "Super baby Egg"
STRINGS.NAMES.MUSHA_EGG_ARONG = "Пушистое Яйцо"
STRINGS.NAMES.MUSHA_EGG_CRACKED_ARONG = "Пушистое Яйцо"
STRINGS.NAMES.MUSHA_EGG = "Яйцо Феникса"
STRINGS.NAMES.MUSHA_EGG_CRACKED = "Яйцо Феникса"
STRINGS.NAMES.MUSHA_EGGS1 = "Яйцо Феникса(УР 2)"
STRINGS.NAMES.MUSHA_EGG_CRACKEDS1 = "Яйцо Феникса"
STRINGS.NAMES.MUSHA_EGGS2 = "Яйцо Феникса(УР 3)"
STRINGS.NAMES.MUSHA_EGG_CRACKEDS2 = "Яйцо Феникса"
STRINGS.NAMES.MUSHA_EGGS3 = "Яйцо Феникса(УР 4)"
STRINGS.NAMES.MUSHA_EGG_CRACKEDS3 = "Яйцо Феникса"
STRINGS.NAMES.MUSHA_EGG1 = "Яйцо Феникса(УР 5)"
STRINGS.NAMES.MUSHA_EGG_CRACKED1 = "Яйцо Феникса"
STRINGS.NAMES.MUSHA_EGG2 = "Яйцо Феникса(УР 6)"
STRINGS.NAMES.MUSHA_EGG_CRACKED2 = "Яйцо Феникса"
STRINGS.NAMES.MUSHA_EGG3 = "Яйцо Феникса(УР 7)"
STRINGS.NAMES.MUSHA_EGG_CRACKED3 = "Яйцо Феникса"
STRINGS.NAMES.MUSHA_EGG8 = "Яйцо Феникса(УР 8)"
STRINGS.NAMES.MUSHA_EGG_CRACKED8 = "Яйцо Феникса"
STRINGS.NAMES.MUSHA_EGG = "Яйцо Феникса"

STRINGS.NAMES.MUSHA_SPORE_FIRE = "Клочок Огня"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_SPORE_FIRE = "Он согреет в зиму."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_ARONG = "Шерстяное Яйцо"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_RANDOM = "Super baby Yamche Egg"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG = "Яйцо Феникса"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGGS1 = "Яйцо Феникса(УР 2)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGGS2 = "Яйцо Феникса(УР 3)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGGS3 = "Яйцо Феникса(УР 4)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG1 = "Яйцо Феникса(УР 5)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG2 = "Яйцо Феникса(УР 6)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG3 = "Яйцо Феникса(УР 7)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG8 = "Яйцо Феникса(УР 8)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED = "Это не мое. Муша думает это бутон Ямши."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKEDS1 = "Это не мое. Муша думает это бутон Ямши."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKEDS2 = "Это не мое. Муша думает это бутон Ямши."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKEDS3 = "Это не мое. Муша думает это бутон Ямши."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED1 = "Это не мое. Муша думает это бутон Ямши."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED2 = "Это не мое. Муша думает это бутон Ямши."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED3 = "Это не мое. Муша думает это бутон Ямши."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_EGG_CRACKED8 = "Это не мое. Муша думает это бутон Ямши."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARONG_BABY = "Расти мой транспорт!\nКоманды:(F1)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARONG = "Быстрейший Бифало в мире!!\nКоманды:(F1)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AROM = "Самая Быстрая Девочка в мире!!\nКоманды:(F1)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONTREE = "Он 'Далл на му'.\nНа древнем языке означает 'Лунное Дерево'.\nКоманды:(F2)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONNUTDRAKE = "Королевский Прислужник"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONNUTDRAKE2 = "Откуда он появился?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONLIGHT_PLANT = "Красивый цвет! Но плохой вкус."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_SMALL = "Какая маленькая птичка!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_SMALL_SUPER = "Какая маленькая птичка!" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEEN = "Он не может спать у меня на голове... \nНо все еще милый."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENR1 = "Он не может спать у меня на голове... \nНо все еще такой милый."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENR2 = "Он не может спать у меня на голове... \nНо все еще такой милый."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENR3 = "Он не может спать у меня на голове... \nНо все еще такой милый."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENR4 = "Он не может спать у меня на голове... \nНо все еще такой милый."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TEENICE = "Он не может спать у меня на голове... \nНо все еще такой милый."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL = "Ямши ест все. Так радостно."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLR1 = "Ямши ест все. Так радостно."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLR2 = "Ямши ест все. Так радостно."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLR3 = "Ямши ест все. Так радостно."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLR4 = "Ямши ест все. Так радостно."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRICE = "Ямши ест все. Так радостно."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL2 = "Какая полезная птица!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR1 = "Какая полезная птица!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR2 = "Какая полезная птица!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR3 = "Какая полезная птица!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR4 = "Какая полезная птица!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRR5 = "Какая полезная птица!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRICE = "Какая полезная птица!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL3 = "Ямши не просто птица. Это мой друг."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR1 = "Ямши не просто птица. Это мой друг."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR2 = "Ямши не просто птица. Это мой друг."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR3 = "Ямши не просто птица. Это мой друг."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR4 = "Ямши не просто птица. Это мой друг."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRR5 = "Ямши не просто птица. Это мой друг."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRICE = "Ямши не просто птица. Это мой друг."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL4 = "Да. Все верно. Мы семья."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR1 = "Да. Все верно. Мы семья."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR2 = "Да. Все верно. Мы семья."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR3 = "Да. Все верно. Мы семья."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR4 = "Да. Все верно. Мы семья."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR5 = "Да. Все верно. Мы семья."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRR6 = "Да. Все верно. Мы семья."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRICE = "Да. Все верно. Мы семья."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALL5 = "Путешествовать вместе. Это здорово."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR1 = "Путешествовать вместе. Это здорово."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR2 = "Путешествовать вместе. Это здорово."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR3 = "Путешествовать вместе. Это здорово."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR4 = "Путешествовать вместе. Это здорово."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR5 = "Путешествовать вместе. Это здорово."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRR6 = "Путешествовать вместе. Это здорово."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TALLRRRRRICE = "Путешествовать вместе. Это здорово."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP1 = "Партнер по выживанию."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP2 = "Партнер по выживанию."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP3 = "Партнер по выживанию."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP4 = "Партнер по выживанию."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP5 = "Партнер по выживанию."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP6 = "Партнер по выживанию."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RP7 = "Партнер по выживанию."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_RPICE = "Партнер по выживанию."
STRINGS.NAMES.GHOSTHOUND = "Призрачная Гончая"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GHOSTHOUND = "Муша призвала призрачную гончую."
STRINGS.NAMES.GHOSTHOUND2 = "Призрачный Щенок"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GHOSTHOUND2 = "Чистая щенячья душа."
STRINGS.NAMES.SHADOWMUSHA = "Тень Муши"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOWMUSHA = "Эта тень похожа на Мушу"
STRINGS.NAMES.TENTACLE_FROST = "Ледяное Щупальце"
STRINGS.NAMES.TENTACLE_SHADOW = "Теневое Щупальце"

STRINGS.RECIPE_DESC.MUSHA_EGG = "Компаньон Ямши (Команды 'Z,V,B')"
STRINGS.RECIPE_DESC.MUSHA_EGG_ARONG = "Компаньон Аронг (Команды 'F1')"
STRINGS.RECIPE_DESC.MUSHA_EGG_RANDOM = "Powerful but eternal baby."
STRINGS.RECIPE_DESC.MOONTREE = "Компаньон Далл (Команды 'F2')"
STRINGS.NAMES.MOONTREE = "Лунное Дерево"
STRINGS.RECIPE_DESC.MUSHA_EGGS1 = "Яйцо Феникса (Ур.2)"
STRINGS.RECIPE_DESC.MUSHA_EGGS2 = "Яйцо Феникса (Ур.3)"
STRINGS.RECIPE_DESC.MUSHA_EGGS3 = "Яйцо Феникса (Ур.4)"
STRINGS.RECIPE_DESC.MUSHA_EGG1 = "Яйцо Феникса (Ур.5)"
STRINGS.RECIPE_DESC.MUSHA_EGG2 = "Яйцо Феникса (Ур.6)"
STRINGS.RECIPE_DESC.MUSHA_EGG3 = "Яйцо Феникса (Ур.7)"
STRINGS.RECIPE_DESC.MUSHA_EGG8 = "Яйцо Феникса (Ур.Макс)"
STRINGS.RECIPE_DESC.REDGEM = "Алхимия Самоцветов"
STRINGS.RECIPE_DESC.BLUEGEM = "Алхимия Самоцветов" 
STRINGS.RECIPE_DESC.GREENGEM = "Алхимия Самоцветов" 
STRINGS.RECIPE_DESC.YELLOWGEM = "Алхимия Самоцветов" 
STRINGS.RECIPE_DESC.ORANGEGEM = "Алхимия Самоцветов" 

STRINGS.NAMES.MOONNUTDRAKE = "Кокобонг"
STRINGS.NAMES.MOONNUTDRAKE2 = "Бооха"
STRINGS.NAMES.MOONBUSH = "Ягодный Куст"
STRINGS.NAMES.MOONLIGHT_PLANT = "Светящаяся Ягода"

STRINGS.NAMES.REDGEM = "Красный самоцвет"
STRINGS.NAMES.BLUEGEM = "Синий самоцвет" 
STRINGS.NAMES.GREENGEM = "Зеленый самоцвет" 
STRINGS.NAMES.YELLOWGEM = "Желтый самоцвет" 
STRINGS.NAMES.ORANGEGEM = "Оранжевый самоцвет" 

STRINGS.NAMES.MUSHASWORD_BASE = "Сломанный Меч"
STRINGS.NAMES.MUSHASWORD = "Клинок Феникса"
STRINGS.NAMES.MUSHASWORD4 = "Секира Феникса"
STRINGS.NAMES.MUSHASWORD_FROST = "Ледяной Клинок Феникса"
STRINGS.RECIPE_DESC.MUSHASWORD_BASE = "Сломанный Клинок Феникса, Вид изменяется"
STRINGS.RECIPE_DESC.MUSHASWORD = "Улучшаемое Оружие, Вид изменяется"
STRINGS.RECIPE_DESC.MUSHASWORD4 = "Улучшаемое Оружие, Топор"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TREASURE = "Муша нашла тебя!"
STRINGS.NAMES.MUSHA_TREASURE = "Сокровище"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ASSASIN_WILSON = "Вилсон?"
STRINGS.NAMES.ASSASIN_WILSON = "Виллсон"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_TREASURE2 = "Муша нашла тебя!"
STRINGS.NAMES.MUSHA_TREASURE2 = "Скрытое место"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHA_HIDDEN_EGG = "Выходи Ямши!"
STRINGS.NAMES.MUSHA_HIDDEN_EGG = "Скрытое место"

STRINGS.RECIPE_DESC.MUSHASWORD_FROST = "Улучшаемое Оружие, Вид изменяется"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHASWORD_BASE = "Это обычный улучшаемый меч."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHASWORD = "Это обычный улучшаемый огненный меч."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHASWORD_FROST = "Это обычный улучшаемый ледяной меч."
STRINGS.NAMES.MUSHA_FLUTE = "Флейта Муши"
STRINGS.RECIPE_DESC.MUSHA_FLUTE = "Лечащая музыка. Ремонт: Светопыль, Светящиеся ягоды"
STRINGS.NAMES.GLOWDUST = "Светопыль"
STRINGS.RECIPE_DESC.GLOWDUST = "Пыль из света, вкусно."

STRINGS.RECIPE_DESC.WORMLIGHT_LESSER = "Ягоды алхимического света"
STRINGS.NAMES.PORTION_E = "Энергетический Напиток"
STRINGS.RECIPE_DESC.PORTION_E = "Энергетический Напиток"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTION_E = "Давай посмотрим.. [Кофейное яблоко: 99%]"
STRINGS.NAMES.CRISTAL = "Кристальная Конфета"
STRINGS.RECIPE_DESC.CRISTAL = "Очень вкусно"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRISTAL = "Похож на обычный кристал"
STRINGS.NAMES.EXP = "Эссенция Энергии"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EXP = "Он дает немного опыта."
STRINGS.NAMES.EXP1000CHEAT = "Эссенция Обмана"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EXP1000CHEAT = "Он дает тонны опыта."
STRINGS.NAMES.FROSTHAMMER = "Морозный Молот"
STRINGS.RECIPE_DESC.FROSTHAMMER = "Улучшается, Ремонтируется, Атака по области(ПКМ)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FROSTHAMMER = "Тяжелый синий друг"
STRINGS.NAMES.BROKEN_FROSTHAMMER = "Ледяная Броня"
STRINGS.RECIPE_DESC.BROKEN_FROSTHAMMER = "Улучшается, Компактная, Холодильник, Отражает"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BROKEN_FROSTHAMMER =  "У нее много функций."
STRINGS.NAMES.PHOENIXSPEAR = "Копье Феникса"
STRINGS.RECIPE_DESC.PHOENIXSPEAR = "Улучшается, Длинный клинок, Лопата"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PHOENIXSPEAR = "Это длинное но очень легкое оружие!"
STRINGS.NAMES.BOWM = "Клинок-Лук"
STRINGS.RECIPE_DESC.BOWM = "Улучшается, Лук(ПКМ)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOWM = "Извини Гадюка, Муша больше тебя любит солнышко."
STRINGS.NAMES.ARROWM = "Стрелы"
STRINGS.RECIPE_DESC.ARROWM = "Обычные Стрелы"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARROWM = "Привет острые малыши"
STRINGS.NAMES.ARROWM_BROKEN = "Сломанная стрела"
STRINGS.RECIPE_DESC.ARROWM_BROKEN = "Сломанная стрела"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARROWM_BROKEN = "Муша может починить их."
STRINGS.NAMES.DUMMY_ARROW0 = "Стрела"
STRINGS.RECIPE_DESC.DUMMY_ARROW0 = "Обычная стрела x2"
STRINGS.NAMES.DUMMY_ARROW1 = "Стрела"
STRINGS.RECIPE_DESC.DUMMY_ARROW1 = "Обычная стрела x2"
STRINGS.NAMES.DUMMY_ARROW2 = "Стрела"
STRINGS.RECIPE_DESC.DUMMY_ARROW2 = "Обычная стрела x2"
STRINGS.NAMES.DUMMY_ARROW3 = "Стрела"
STRINGS.RECIPE_DESC.DUMMY_ARROW3 = "Обычная стрела x2"
STRINGS.NAMES.DUMMY_ARROW4 = "Стрела"
STRINGS.RECIPE_DESC.DUMMY_ARROW4 = "Обычная стрела x6"
STRINGS.NAMES.HAT_MPHOENIX = "Шлем Феникса"
STRINGS.RECIPE_DESC.HAT_MPHOENIX = "Улучшается, Маска(ПКМ)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MPHOENIX = "Средневековый шлем"
STRINGS.NAMES.HAT_MPRINCESS = "Корона Принцессы Щенка"
STRINGS.RECIPE_DESC.HAT_MPRINCESS = "Щит, Восстановление рассудка, Смена вида"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MPRINCESS = "Маленькая золотая корона"
STRINGS.NAMES.HAT_MCROWN = "Корона Королевы Щенка"
STRINGS.RECIPE_DESC.HAT_MCROWN = "Щит, Восстановление рассудка, Специальная опция"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MCROWN = "Выглядит так мило."
STRINGS.NAMES.HAT_MBUNNY = "Заячий Шлем"
STRINGS.RECIPE_DESC.HAT_MBUNNY = "Улучшается, Очки(ПКМ)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MBUNNY = "Похоже на заячьи ушки."
STRINGS.NAMES.HAT_MBUNNYA = "Шлем Стального Зайца"
STRINGS.RECIPE_DESC.HAT_MBUNNYA = "Улучшается, Светит, Очки(ПКМ)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MBUNNYA = "Супер герой 'Стальной Заяц'!"
STRINGS.NAMES.HAT_MWILDCAT = "Шлем Стального Кота"
STRINGS.RECIPE_DESC.HAT_MWILDCAT = "Улучшается, Светит (ПКМ)"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_MWILDCAT = "Супер герой 'Стальной Кот!"
STRINGS.NAMES.ARMOR_MUSHAA = "Броня Муши"
STRINGS.RECIPE_DESC.ARMOR_MUSHAA = "Улучшается, Компактная, Рюкзак"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_MUSHAA = "Это волнистое платье."
STRINGS.NAMES.ARMOR_MUSHAB = "Броня Принцессы"
STRINGS.RECIPE_DESC.ARMOR_MUSHAB = "Улучшается, Рюкзак, Согревает /Охлаждает"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_MUSHAB = "Оно волнистое, но безопасное." 
-----------------random -name
STRINGS.PHOENIXS=
{    
"Капитан Ямши","Мощный Ямши","Стальной Ямши","Каменный Ямши","Ямши","Храбрый Ямши","Милый Ямши","Совиный Ямши","Солнечный Ямши","Лунный Ямши","Сеульский Ямши","Сури Ямши","Вилья Ямши","Солнечный Ямши","Солнечносветный","Мушин Ямши","Мелиса Ямши","Лидия Ямши ","Битворожденный Ямши ","Серый Ямши","Небесный Ямши","Люции Ямши","Каджитный Ямши","Свиной Ямши","Мьёлл Ямши","Львиный Ямши","Мури Ямши","Исолда Ямши","Райа Ямши","Фалкас Ямши","Вилкас Ямши","Айла Ямши","Хутер Ямши","Охотничий Ямши","Королевский Ямши","Огненный Ямши","Цицеро Ямши","Top Ямши","Лина Ямши","Тоторо Ямши","Юна Ямши","Снежный Ямши","Белый Ямши","Мелиса Ямши","Рифтовый Ямши","Звездный Ямши","Вильгельмский Ямши","Пхо Ямши","Шустрый Ямши","Кивис Ямши","Коко Ямши","Лунный Ямши","Пицца Ямши","Сахарный Ямши","Орк Ямши","Эльф Ямши","Рыцарь Ямши","Влад Ямши","Азерот Ямши","Таурин Ямши","Тролль Ямши","Рабский Ямши","Наругар Ямши","Янтух Ямши","Тиран Ямши","Медовый Ямши","Горлум Ямши","Душевный Ямши","Эсмеральда Ямши","Плювиа Ямши","Дораемон Ямши","Долли Ямши","Яблочный Ямши","ИУ Ямши","Гендальф Ямши","Фродо Ямши","Сэм Ямши","Леголаз Ямши","Гимли Ямши","Боромир Ямши","Вилксон Ямши","Виллоу Ямши","Вольфконг Ямши","Венил Ямши","ВХ79 Ямши","Виккерби Ямши","Беспокойный Ямши","Векс Ямши","Максимус Ямши","Вигфридум Ямши","Вебберов Ямши","Наруто Ямши","Сасуке Ямши","Колдовской Ямши","Лука Ямши","Аронг Ямши","Щенок Ямши",
 }
STRINGS.ARONG=
{    
"Капитан Аронг","Мощный Аронг","Стальной Аронг","Каменный Аронг","Ямши","Храбрый Аронг","Милый Аронг","Совиный Аронг","Солнечный Аронг","Лунный Аронг","Сеульский Аронг","Сури Аронг","Вилья Аронг","Солнечный Аронг","Солнечносветный","Мушин Аронг","Мелиса Аронг","Лидия Аронг ","Битворожденный Аронг ","Серый Аронг","Небесный Аронг","Люции Аронг","Каджитный Аронг","Свиной Аронг","Мьёлл Аронг","Львиный Аронг","Мури Аронг","Исолда Аронг","Райа Аронг","Фалкас Аронг","Вилкас Аронг","Айла Аронг","Хутер Аронг","Охотничий Аронг","Королевский Аронг","Огненный Аронг","Цицеро Аронг","Top Аронг","Лина Аронг","Тоторо Аронг","Юна Аронг","Снежный Аронг","Белый Аронг","Мелиса Аронг","Рифтовый Аронг","Звездный Аронг","Вильгельмский Аронг","Пхо Аронг","Шустрый Аронг","Кивис Аронг","Коко Аронг","Лунный Аронг","Пицца Аронг","Сахарный Аронг","Орк Аронг","Эльф Аронг","Рыцарь Аронг","Влад Аронг","Азерот Аронг","Таурин Аронг","Тролль Аронг","Рабский Аронг","Наругар Аронг","Янтух Аронг","Тиран Аронг","Медовый Аронг","Горлум Аронг","Душевный Аронг","Эсмеральда Аронг","Плювиа Аронг","Дораемон Аронг","Долли Аронг","Яблочный Аронг","ИУ Аронг","Гендальф Аронг","Фродо Аронг","Сэм Аронг","Леголаз Аронг","Гимли Аронг","Боромир Аронг","Вилксон Аронг","Виллоу Аронг","Вольфконг Аронг","Венил Аронг","ВХ79 Аронг","Виккерби Аронг","Беспокойный Аронг","Векс Аронг","Максимус Аронг","Вигфридум Аронг","Вебберов Аронг","Наруто Аронг","Сасуке Аронг","Колдовской Аронг","Лука Аронг","Аронг Аронг","Щенок Аронг",
 }
 STRINGS.AROM=
{    
"Капитан Аром","Мощный Аром","Стальной Аром","Каменный Аром","Ямши","Храбрый Аром","Милый Аром","Совиный Аром","Солнечный Аром","Лунный Аром","Сеульский Аром","Сури Аром","Вилья Аром","Солнечный Аром","Солнечносветный","Мушин Аром","Мелиса Аром","Лидия Аром ","Битворожденный Аром ","Серый Аром","Небесный Аром","Люции Аром","Каджитный Аром","Свиной Аром","Мьёлл Аром","Львиный Аром","Мури Аром","Исолда Аром","Райа Аром","Фалкас Аром","Вилкас Аром","Айла Аром","Хутер Аром","Охотничий Аром","Королевский Аром","Огненный Аром","Цицеро Аром","Top Аром","Лина Аром","Тоторо Аром","Юна Аром","Снежный Аром","Белый Аром","Мелиса Аром","Рифтовый Аром","Звездный Аром","Вильгельмский Аром","Пхо Аром","Шустрый Аром","Кивис Аром","Коко Аром","Лунный Аром","Пицца Аром","Сахарный Аром","Орк Аром","Эльф Аром","Рыцарь Аром","Влад Аром","Азерот Аром","Таурин Аром","Тролль Аром","Рабский Аром","Наругар Аром","Янтух Аром","Тиран Аром","Медовый Аром","Горлум Аром","Душевный Аром","Эсмеральда Аром","Плювиа Аром","Дораемон Аром","Долли Аром","Яблочный Аром","ИУ Аром","Гендальф Аром","Фродо Аром","Сэм Аром","Леголаз Аром","Гимли Аром","Боромир Аром","Вилксон Аром","Виллоу Аром","Вольфконг Аром","Венил Аром","ВХ79 Аром","Виккерби Аром","Беспокойный Аром","Векс Аром","Максимус Аром","Вигфридум Аром","Вебберов Аром","Наруто Аром","Сасуке Аром","Колдовской Аром","Лука Аром","Аронг Аром","Щенок Аром",
 }
STRINGS.DALL=
{    
"Капитан Далл","Мощный Далл","Стальной Далл","Каменный Далл","Ямши","Храбрый Далл","Милый Далл","Совиный Далл","Солнечный Далл","Лунный Далл","Сеульский Далл","Сури Далл","Вилья Далл","Солнечный Далл","Солнечносветный","Мушин Далл","Мелиса Далл","Лидия Далл ","Битворожденный Далл ","Серый Далл","Небесный Далл","Люции Далл","Каджитный Далл","Свиной Далл","Мьёлл Далл","Львиный Далл","Мури Далл","Исолда Далл","Райа Далл","Фалкас Далл","Вилкас Далл","Айла Далл","Хутер Далл","Охотничий Далл","Королевский Далл","Огненный Далл","Цицеро Далл","Top Далл","Лина Далл","Тоторо Далл","Юна Далл","Снежный Далл","Белый Далл","Мелиса Далл","Рифтовый Далл","Звездный Далл","Вильгельмский Далл","Пхо Далл","Шустрый Далл","Кивис Далл","Коко Далл","Лунный Далл","Пицца Далл","Сахарный Далл","Орк Далл","Эльф Далл","Рыцарь Далл","Влад Далл","Азерот Далл","Таурин Далл","Тролль Далл","Рабский Далл","Наругар Далл","Янтух Далл","Тиран Далл","Медовый Далл","Горлум Далл","Душевный Далл","Эсмеральда Далл","Плювиа Далл","Дораемон Далл","Долли Далл","Яблочный Далл","ИУ Далл","Гендальф Далл","Фродо Далл","Сэм Далл","Леголаз Далл","Гимли Далл","Боромир Далл","Вилксон Далл","Виллоу Далл","Вольфконг Далл","Венил Далл","ВХ79 Далл","Виккерби Далл","Беспокойный Далл","Векс Далл","Максимус Далл","Вигфридум Далл","Вебберов Далл","Наруто Далл","Сасуке Далл","Колдовской Далл","Лука Далл","Аронг Далл","Щенок Далл",
 }
 
  --adds
STRINGS.MUSHA_YAMCHE = "[ Ямши ]"
STRINGS.MUSHA_HEALTH_HUNGER = "Здоровье/Голод"
STRINGS.MUSHA_HEALTH = "Здоровье"
STRINGS.MUSHA_HUNGER = "Голод" 
STRINGS.MUSHA_TALK_ORDER_PET_FOLLOW = "Пошли со мной?"
STRINGS.MUSHA_TALK_ORDER_PET_STAY = "Стой тут."
STRINGS.MUSHA_TALK_ORDER_PET_LOST = "Муша не видит своего питомца."
STRINGS.MUSHA_TALK_ORDER_YAMCHE_LEVEL1 = "Он ещё слишком юн."
STRINGS.MUSHA_TALK_NEED_SPELLPOWER = "Не хватает... [Мана].."
STRINGS.MUSHA_MYPOWER_CALL_LIGHTNING = "Призвать молнию"
STRINGS.MUSHA_MYPOWER_SMITE = "Мощный удар"

STRINGS.MUSHA_ACTION_REPAIR = "Ремонт"
STRINGS.MUSHA_ACTION_ADDFUEL = "Добавить топливо"