return {
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1279875294"]={
    configuration_options={
      BIGGRIDSIZE=2,
      BUILDGRID=true,
      COLORS="blackwhiteoutline",
      CONTROLLEROFFSET=false,
      CTRL=false,
      FLOODGRIDSIZE=5,
      GEOMETRY="SQUARE",
      GEOMETRYTOGGLEKEY="V",
      HIDEBLOCKED=false,
      HIDECURSOR=false,
      HIDEPLACER=false,
      KEYBOARDTOGGLEKEY="B",
      MEDGRIDSIZE=6,
      REDUCECHESTSPACING=true,
      SHOWMENU=true,
      SHOWTILE=false,
      SMALLGRIDSIZE=10,
      TIMEBUDGET=0.1 
    },
    enabled=true 
  },
  ["workshop-1378549454"]={
    configuration_options={
      ["MemSpikeFix:"]=false,
      MemSpikeFixmaster_override=true,
      ["MemSpikeFixworkshop-1207269058"]="default",
      ["MemSpikeFixworkshop-1279875294"]="default",
      ["MemSpikeFixworkshop-1595631294"]="default",
      ["MemSpikeFixworkshop-347079953"]="default",
      ["MemSpikeFixworkshop-351325790"]="default",
      ["MemSpikeFixworkshop-356398534"]="default",
      ["MemSpikeFixworkshop-362175979"]="default",
      ["MemSpikeFixworkshop-365119238"]="default",
      ["MemSpikeFixworkshop-374550642"]="default",
      ["MemSpikeFixworkshop-375850593"]="default",
      ["MemSpikeFixworkshop-375859599"]="default",
      ["MemSpikeFixworkshop-376108724"]="default",
      ["MemSpikeFixworkshop-376333686"]="default",
      ["MemSpikeFixworkshop-378160973"]="default",
      ["MemSpikeFixworkshop-380423963"]="default",
      ["MemSpikeFixworkshop-382177939"]="default",
      ["MemSpikeFixworkshop-396026892"]="default",
      ["MemSpikeFixworkshop-444235588"]="default",
      ["MemSpikeFixworkshop-458940297"]="default",
      ["MemSpikeFixworkshop-466732225"]="default",
      ["MemSpikeFixworkshop-483347719"]="default",
      ["MemSpikeFixworkshop-503187227"]="default",
      ["MemSpikeFixworkshop-543945797"]="default",
      ["MemSpikeFixworkshop-609051112"]="default",
      ["MemSpikeFixworkshop-666155465"]="default",
      ["MemSpikeFixworkshop-727774324"]="default",
      ["MemSpikeFixworkshop-758532836"]="default",
      ["MemSpikeFixworkshop-780009141"]="default",
      ["MemSpikeFixworkshop-890028129"]="default",
      ["MemSpikeFixworkshop-956206484"]="default",
      craftinghighlight=false 
    },
    enabled=true 
  },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      Digornot=false,
      DragonflyChest=false,
      Icebox=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-356398534"]={ configuration_options={  }, enabled=true },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-458940297"]={
    configuration_options={
      DFV_ClientPrediction="default",
      DFV_FueledSettings="default",
      DFV_Language="EN",
      DFV_MinimalMode="default",
      DFV_PercentReplace="default",
      DFV_ShowACondition="default",
      DFV_ShowADefence="default",
      DFV_ShowAType="default",
      DFV_ShowDamage="default",
      DFV_ShowFireTime="default",
      DFV_ShowInsulation="default",
      DFV_ShowTemperature="default",
      DFV_ShowUses="default" 
    },
    enabled=true 
  },
  ["workshop-543945797"]={
    configuration_options={
      amount_of_numbers="default",
      display_mode="waving",
      dmg_only="on",
      number_size="default",
      show_decimal_points="no" 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  } 
}