
local function sailface(prefab)
	AddPrefabPostInit(prefab, function(inst)
		inst.AnimState:OverrideSymbol("face_sail", "swap_sailface_".. inst.prefab, "face_sail")
	end)
end
sailface("wilson")
sailface("willow")
sailface("wolfgang")
sailface("wendy")
sailface("wx78")
sailface("wickerbottom")
sailface("woodie")
sailface("wes")
sailface("waxwell")
sailface("wathgrithr")
sailface("webber")
sailface("winona")
sailface("musha")
