return {
  ["workshop-1378549454"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-1595631294"]={
    ["configuration_options"]={
      ["BundleItems"]=false,
      ["Digornot"]=false,
      ["DragonflyChest"]=false,
      ["Icebox"]=false 
    },
    ["enabled"]=true 
  },
  ["workshop-347079953"]={
    ["configuration_options"]={ ["DFV_Language"]="EN", ["DFV_MinimalMode"]="default" },
    ["enabled"]=true 
  },
  ["workshop-362175979"]={ ["configuration_options"]={ ["Draw over FoW"]="disabled" }, ["enabled"]=true },
  ["workshop-375850593"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-375859599"]={
    ["configuration_options"]={
      ["divider"]=5,
      ["random_health_value"]=0,
      ["random_range"]=0,
      ["show_type"]=0,
      ["unknwon_prefabs"]=1,
      ["use_blacklist"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-378160973"]={
    ["configuration_options"]={
      ["ENABLEPINGS"]=true,
      ["FIREOPTIONS"]=2,
      ["OVERRIDEMODE"]=false,
      ["SHAREMINIMAPPROGRESS"]=true,
      ["SHOWFIREICONS"]=true,
      ["SHOWPLAYERICONS"]=true,
      ["SHOWPLAYERSOPTIONS"]=2 
    },
    ["enabled"]=true 
  },
  ["workshop-382164446"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-458940297"]={
    ["configuration_options"]={
      ["DFV_ClientPrediction"]="default",
      ["DFV_FueledSettings"]="default",
      ["DFV_Language"]="EN",
      ["DFV_MinimalMode"]="default",
      ["DFV_PercentReplace"]="default",
      ["DFV_ShowACondition"]="default",
      ["DFV_ShowADefence"]="default",
      ["DFV_ShowAType"]="default",
      ["DFV_ShowDamage"]="default",
      ["DFV_ShowFireTime"]="default",
      ["DFV_ShowInsulation"]="default",
      ["DFV_ShowTemperature"]="default",
      ["DFV_ShowUses"]="default" 
    },
    ["enabled"]=true 
  },
  ["workshop-543945797"]={
    ["configuration_options"]={
      ["amount_of_numbers"]="default",
      ["display_mode"]="waving",
      ["dmg_only"]="on",
      ["number_size"]="default",
      ["show_decimal_points"]="no" 
    },
    ["enabled"]=true 
  },
  ["workshop-666155465"]={
    ["configuration_options"]={
      ["food_estimation"]=-1,
      ["food_order"]=0,
      ["food_style"]=0,
      ["lang"]="auto",
      ["show_food_units"]=-1 
    },
    ["enabled"]=true 
  },
  ["workshop-758532836"]={
    ["configuration_options"]={
      ["AUTOPAUSECONSOLE"]=false,
      ["AUTOPAUSEMAP"]=false,
      ["AUTOPAUSESINGLEPLAYER"]=true,
      ["ENABLECLIENTPAUSING"]=false,
      ["ENABLEHOTKEY"]=false,
      ["KEYBOARDTOGGLEKEY"]="P" 
    },
    ["enabled"]=true 
  } 
}