return {
  ["workshop-1595631294"]={
    ["configuration_options"]={
      ["BundleItems"]=false,
      ["Digornot"]=false,
      ["DragonflyChest"]=false,
      ["Icebox"]=false 
    },
    ["enabled"]=true 
  },
  ["workshop-347079953"]={
    ["configuration_options"]={ ["DFV_Language"]="EN", ["DFV_MinimalMode"]="default" },
    ["enabled"]=true 
  },
  ["workshop-362175979"]={ ["configuration_options"]={ ["Draw over FoW"]="disabled" }, ["enabled"]=true },
  ["workshop-375850593"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-375859599"]={
    ["configuration_options"]={
      ["divider"]=5,
      ["random_health_value"]=0,
      ["random_range"]=0,
      ["show_type"]=0,
      ["unknwon_prefabs"]=1,
      ["use_blacklist"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-378160973"]={
    ["configuration_options"]={
      ["ENABLEPINGS"]=true,
      ["FIREOPTIONS"]=2,
      ["OVERRIDEMODE"]=false,
      ["SHAREMINIMAPPROGRESS"]=true,
      ["SHOWFIREICONS"]=true,
      ["SHOWPLAYERICONS"]=true,
      ["SHOWPLAYERSOPTIONS"]=2 
    },
    ["enabled"]=true 
  },
  ["workshop-382164446"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-458940297"]={
    ["configuration_options"]={
      ["DFV_ClientPrediction"]="default",
      ["DFV_FueledSettings"]="default",
      ["DFV_Language"]="EN",
      ["DFV_MinimalMode"]="default",
      ["DFV_PercentReplace"]="default",
      ["DFV_ShowACondition"]="default",
      ["DFV_ShowADefence"]="default",
      ["DFV_ShowAType"]="default",
      ["DFV_ShowDamage"]="default",
      ["DFV_ShowFireTime"]="default",
      ["DFV_ShowInsulation"]="default",
      ["DFV_ShowTemperature"]="default",
      ["DFV_ShowUses"]="default" 
    },
    ["enabled"]=true 
  },
  ["workshop-503187227"]={
    ["configuration_options"]={
      [""]=0,
      ["AltarRoomOption"]=2,
      ["AncientGuardianSpawn"]=1,
      ["BrokenAltarOption"]=2,
      ["CaveBaseOption"]=12,
      ["ChessSpot1Option"]=1,
      ["ChessSpot2Option"]=1,
      ["ChessSpot3Option"]=1,
      ["Chessy1Option"]=2,
      ["Chessy2Option"]=2,
      ["Chessy3Option"]=2,
      ["Chessy4Option"]=2,
      ["Chessy5Option"]=2,
      ["Chessy6Option"]=2,
      ["DeciduousPondOption"]=3,
      ["DefaultPigkingOption"]=1,
      ["DragonflySpawn"]=1,
      ["FarmplotOption"]=8,
      ["FisherPigOption"]=1,
      ["GlobalBiomeSize"]=10,
      ["GrottoOption"]=20,
      ["InfusedWorldsRandomOptionalBiomes"]=15,
      ["LightsOutStartingItems"]=0,
      ["LivingTreeOption"]=2,
      ["MacTuskCityOption"]=1,
      ["MacTuskTownOption"]=1,
      ["Maxwell1Option"]=1,
      ["Maxwell2Option"]=1,
      ["Maxwell3Option"]=1,
      ["Maxwell4Option"]=1,
      ["Maxwell5Option"]=1,
      ["Maxwell6Option"]=1,
      ["Maxwell7Option"]=1,
      ["MermShrineOption"]=0,
      ["MilitaryEntranceOption"]=1,
      ["MooseSpawn"]=9,
      ["MushBaseOption"]=12,
      ["OverworldNightmarePhase"]=1,
      ["PigGuardsOption"]=2,
      ["PigShrineOption"]=0,
      ["PigTownOption"]=2,
      ["RabbitTownOption"]=8,
      ["RandomOptionalBiomes"]=6,
      ["RandomOptionalCaveBiomes"]=8,
      ["ResurrectionStoneOption"]=2,
      ["RuinedBaseOption"]=2,
      ["RuinsCampOption"]=5,
      ["SimpleBaseOption"]=2,
      ["SinkBaseOption"]=12,
      ["SpiralOption"]=2,
      ["StoneHengeOption"]=8,
      ["SwampPigOption"]=1,
      ["TorchPigkingOption"]=1,
      ["VillageSquareOption"]=2 
    },
    ["enabled"]=true 
  },
  ["workshop-543945797"]={
    ["configuration_options"]={
      ["amount_of_numbers"]="default",
      ["display_mode"]="waving",
      ["dmg_only"]="on",
      ["number_size"]="default",
      ["show_decimal_points"]="no" 
    },
    ["enabled"]=true 
  },
  ["workshop-666155465"]={
    ["configuration_options"]={
      ["food_estimation"]=-1,
      ["food_order"]=0,
      ["food_style"]=0,
      ["lang"]="auto",
      ["show_food_units"]=-1 
    },
    ["enabled"]=true 
  } 
}